/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description No DB, no readiness check (SPEC §3.8) — always cheap and correct.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description DB ping + migrations current + queue not saturated (SPEC §3.8). Fails during the graceful-shutdown drain sequence.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version, retention, vendors seen, data-quality summary */
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter option lists for the session/event/tool-call UIs */
        get: operations["getFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session detail with aggregates */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw events of one session, keyset-paginated */
        get: operations["getSessionTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turn list with per-turn aggregates */
        get: operations["listSessionTurns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/tool-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tool calls of one session */
        get: operations["listSessionToolCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/subagents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subagent tree with cost attribution */
        get: operations["getSessionSubagents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE stream of one session's events and projection updates */
        get: operations["streamSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-session event search */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with full attrs (the detail drawer) */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tool-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-session tool-call list — the decision-provenance drill-down */
        get: operations["listToolCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scalar KPIs for a window */
        get: operations["getAnalyticsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bucketed series, dense and zero-filled */
        get: operations["getAnalyticsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-N by dimension */
        get: operations["getAnalyticsBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accept/reject x decision_source matrix */
        get: operations["getAnalyticsDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality/unknown-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grouped unmapped event_names, one raw sample each */
        get: operations["getQualityUnknownKinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality/hook-latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** hook.execution_end percentiles by hook_event */
        get: operations["getQualityHookLatency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE firehose across all sessions */
        get: operations["streamAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP logs export
         * @description Standard OTLP/HTTP log export (https://opentelemetry.io/docs/specs/otlp/#otlphttp). Body is the opaque OTLP ExportLogsServiceRequest, protobuf or JSON-encoded per Content-Type — described here as opaque object/binary rather than modeled field-by-field, since OTLP's own spec is the source of truth for that wire format.
         */
        post: operations["ingestLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP metrics export
         * @description Standard OTLP/HTTP metrics export; body is the opaque OTLP ExportMetricsServiceRequest (see /v1/logs's description).
         */
        post: operations["ingestMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP traces export (accepted, not stored)
         * @description Standard OTLP/HTTP traces export; body is the opaque OTLP ExportTraceServiceRequest (see /v1/logs's description). Argus has no trace model (SPEC §1) — accepted and discarded so a fully-configured OTel exporter never errors.
         */
        post: operations["ingestTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/hook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claude Code / vendor hooks webhook
         * @description One raw hook payload per call (SPEC §1.1, §3.5). Shape varies by hook_event and vendor, so the body is documented as an opaque object rather than one fixed schema.
         */
        post: operations["ingestHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OKStatus: {
            /**
             * @description Argus-computed liveness state, not vendor vocabulary.
             * @enum {string}
             */
            status: "ok";
        };
        ReadyStatus: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            migrations: "current";
        };
        /** @description RFC 9457 problem+json (SPEC §4.1). type is a stable urn:argus:error:<slug> from Argus's own error catalog (see server/internal/httpapi/problem.go); left as a plain string rather than enumerated here so a future URN never needs a spec-only migration to become valid. */
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            errors?: {
                [key: string]: unknown;
            }[];
        };
        PageInfo: {
            next_cursor: string | null;
            has_more: boolean;
        };
        IngestAck: {
            /** @enum {string} */
            status: "accepted";
        };
        /**
         * @description Argus's own closed event taxonomy (SPEC §1.4) — one of the four closed vocabularies SPEC §0 permits.
         * @enum {string}
         */
        Kind: "session.start" | "session.end" | "turn.start" | "turn.end" | "turn.prompt_expanded" | "llm.request" | "llm.error" | "llm.refusal" | "llm.request_body" | "llm.response_body" | "assistant.message" | "tool.pre" | "tool.decision" | "tool.permission_request" | "tool.result" | "tool.batch" | "subagent.start" | "subagent.stop" | "task.created" | "task.completed" | "permission.mode_changed" | "hook.registered" | "hook.execution_start" | "hook.execution_end" | "fs.file_changed" | "workspace.cwd_changed" | "workspace.directory_added" | "workspace.config_changed" | "workspace.instructions_loaded" | "workspace.worktree_created" | "workspace.worktree_removed" | "context.compact_start" | "context.compact_end" | "mcp.connection" | "mcp.elicitation" | "mcp.elicitation_result" | "agent.auth" | "agent.setup" | "agent.plugin" | "agent.internal_error" | "agent.notification" | "agent.idle" | "unknown";
        /**
         * @description Provenance pipeline (SPEC §1.3) — Argus-closed, one of the four permitted taxonomies.
         * @enum {string}
         */
        EventSource: "otel_log" | "otel_metric" | "hook" | "sim";
        /**
         * @description The echoed ?source= toggle on analytics responses (SPEC §4.3): which source table was aggregated. Distinct from EventSource (per-event provenance) — an Argus-invented request/response concept, not a vendor value.
         * @enum {string}
         */
        AnalyticsSourceValue: "event" | "metric";
        /**
         * @description Tool-call correlation confidence (SPEC §1.6) — Argus-closed.
         * @enum {string}
         */
        Correlation: "exact" | "otel_only" | "hook_only" | "heuristic";
        /**
         * @description Argus-computed session lifecycle state (SPEC §1.7) — closed, unlike vendor vocabulary.
         * @enum {string}
         */
        SessionStatus: "active" | "ended" | "abandoned" | "unknown";
        /**
         * @description Argus-computed turn lifecycle state (SPEC §2.1) — closed.
         * @enum {string}
         */
        TurnStatus: "open" | "complete" | "failed";
        /**
         * @description Argus-computed subagent lifecycle state (SPEC §2.3) — closed.
         * @enum {string}
         */
        SubagentStatus: "running" | "complete" | "failed" | "unknown";
        /** @enum {string} */
        TimeseriesMetric: "cost" | "tokens" | "sessions" | "turns" | "api_requests" | "api_errors" | "tool_calls" | "tool_rejects" | "loc";
        TokenUsage: {
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
            /** Format: int64 */
            cache_read: number;
            /** Format: int64 */
            cache_creation: number;
        };
        /** @description by_query_source keys are raw agent-supplied query_source values, passed through verbatim (SPEC §1.9) — never mapped onto a main/subagent semantic. */
        SessionCost: {
            usd: number;
            reported_usd: number;
            estimated_usd: number;
            estimated_share: number;
            by_query_source: {
                [key: string]: number;
            };
            dominant_query_source: string;
            other_query_source_usd: number;
        };
        SessionSummary: {
            id: string;
            /** @description Agent-agnostic core text (claude_code, codex, gemini_cli, unknown); deliberately unconstrained. */
            vendor: string;
            project: string;
            cwd: string;
            status: components["schemas"]["SessionStatus"];
            /** @description Vendor-supplied session start reason; unconstrained (SPEC §0). */
            start_type: string;
            /**
             * Format: date-time
             * @description NULL until session.start is seen (SPEC §1.7).
             */
            started_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
            /** Format: date-time */
            last_event_at: string;
            /** Format: int64 */
            duration_ms: number | null;
            turn_count: number;
            /** Format: int64 */
            event_count: number;
            tool_call_count: number;
            tool_reject_count: number;
            subagent_count: number;
            error_count: number;
            tokens: components["schemas"]["TokenUsage"];
            cost: components["schemas"]["SessionCost"];
            models: string[];
            /** @description True when no session.start was ever seen (stub-on-reference, SPEC §1.7). */
            partial: boolean;
            app_version: string;
            entrypoint: string;
            /** @description Vendor-supplied, free-form; a live capture found "wsl-Ubuntu" outside any documented enum. */
            terminal_type: string;
        };
        SessionsListResponse: {
            data: components["schemas"]["SessionSummary"][];
            page: components["schemas"]["PageInfo"];
        };
        PermissionModeChange: {
            /** Format: date-time */
            ts: string;
            /** @description Vendor-supplied permission_mode value; unconstrained. */
            from: string;
            /** @description Vendor-supplied permission_mode value; unconstrained. */
            to: string;
            trigger: string;
        };
        ToolUsageSummary: {
            tool_name: string;
            calls: number;
            rejects: number;
            p50_ms: number | null;
        };
        SessionDecisionSummary: {
            accept: number;
            reject: number;
            /** @description Keys are raw decision_source values, unconstrained (SPEC §1.9). */
            by_source: {
                [key: string]: number;
            };
            exact_share: number;
        };
        SessionHookLatency: {
            /** Format: int64 */
            p50_ms: number;
            /** Format: int64 */
            p95_ms: number;
            by_hook_event: {
                [key: string]: number;
            };
        };
        SessionDetail: components["schemas"]["SessionSummary"] & {
            permission_mode_history: components["schemas"]["PermissionModeChange"][];
            top_tools: components["schemas"]["ToolUsageSummary"][];
            decision_summary: components["schemas"]["SessionDecisionSummary"];
            sources_seen: components["schemas"]["EventSource"][];
            raw_events_expired: boolean;
            hook_latency: components["schemas"]["SessionHookLatency"] | null;
            /** Format: date-time */
            first_seen_at: string;
            user: string;
            organization_id: string;
        };
        /** @description The timeline/event-search row shape (SPEC §4.3). fields=slim (default) omits attrs. */
        TimelineEvent: {
            event_ref: string;
            /** Format: int64 */
            seq: number;
            id: string;
            /** Format: date-time */
            ts: string;
            session_id: string;
            prompt_id: string | null;
            kind: components["schemas"]["Kind"];
            /** @description Unprefixed vendor raw event name (SPEC §1.5.1); provenance, not a Kind. */
            event_name: string;
            source: components["schemas"]["EventSource"];
            vendor: string;
            tool_name: string | null;
            tool_use_id: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            decision: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            decision_source: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            tool_source: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            query_source: string | null;
            model: string | null;
            tokens: components["schemas"]["TokenUsage"] | null;
            cost: number | null;
            duration_ms: number | null;
            success: boolean | null;
            error_type: string | null;
            /** @description Hook payloads only, never on OTel log events (SPEC §1.9). */
            agent_id: string | null;
            agent_type: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            permission_mode: string | null;
            file_path: string | null;
            clock_skewed: boolean;
        };
        EventDetail: components["schemas"]["TimelineEvent"] & {
            /** @description Full flattened source payload, including the promoted fields above (SPEC §1.3). */
            attrs: {
                [key: string]: unknown;
            };
        };
        TimelineListResponse: {
            data: components["schemas"]["TimelineEvent"][];
            page: components["schemas"]["PageInfo"];
        };
        Turn: {
            session_id: string;
            prompt_id: string;
            turn_index: number | null;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
            /** Format: date-time */
            first_seen_at: string;
            /** Format: date-time */
            last_event_at: string;
            duration_ms: number | null;
            status: components["schemas"]["TurnStatus"];
            api_request_count: number;
            tool_call_count: number;
            tool_reject_count: number;
            error_count: number;
            /** Format: int64 */
            input_tokens: number;
            /** Format: int64 */
            output_tokens: number;
            /** Format: int64 */
            cache_read_tokens: number;
            /** Format: int64 */
            cache_creation_tokens: number;
            cost_usd: number;
            cost_estimated_usd: number;
            models: string[];
        };
        TurnsListResponse: {
            data: components["schemas"]["Turn"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @description Cross-session/session-scoped tool-call row (SPEC §2.3, §4.2). No worked JSON example is given in SPEC §4.3 for this endpoint; field names mirror internal/model.ToolCall's Go fields snake_cased for consistency with every other wire shape in this file. */
        ToolCall: {
            id: string;
            session_id: string;
            prompt_id: string | null;
            tool_use_id: string | null;
            tool_name: string;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            tool_source: string | null;
            /** @description Hook-sourced only (SPEC §1.9). */
            agent_id: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            decision: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            decision_source: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0, §1.9). */
            permission_mode: string | null;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            decided_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
            duration_ms: number | null;
            /** @description decided_at - started_at, the human/permission latency (SPEC §2.3). */
            wait_ms: number | null;
            success: boolean | null;
            error_type: string | null;
            file_path: string | null;
            input_size_bytes: number | null;
            result_size_bytes: number | null;
            correlation: components["schemas"]["Correlation"];
            event_count: number;
        };
        ToolCallsListResponse: {
            data: components["schemas"]["ToolCall"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @description cost_usd is always null in v1 (SPEC §1.9); tool_call_count is null when the session has no hook coverage, never 0. */
        SubagentNode: {
            agent_id: string;
            parent_agent_id: string | null;
            /** @description Vendor-supplied; unconstrained (SPEC §0). */
            agent_type: string;
            depth: number;
            status: components["schemas"]["SubagentStatus"];
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
            spawn_tool_use_id?: string;
            tool_call_count: number | null;
            cost_usd: number | null;
            children: components["schemas"]["SubagentNode"][];
        };
        SubagentCostAttribution: {
            by_query_source: {
                [key: string]: number;
            };
            dominant_query_source: string;
            other_query_source_usd: number;
            /** @description Always false in v1 (SPEC §1.9). */
            per_node_available: boolean;
            note: string;
        };
        SubagentTree: {
            data: components["schemas"]["SubagentNode"][];
            cost_attribution: components["schemas"]["SubagentCostAttribution"];
        };
        Window: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** @enum {string} */
            bucket: "hour" | "day";
        };
        /** @description Fleet-level cost shape — no by_query_source split (SPEC §4.3; that split lives only on the session). */
        Cost: {
            usd: number;
            reported_usd: number;
            estimated_usd: number;
            estimated_share: number;
        };
        LOC: {
            /** Format: int64 */
            added: number;
            /** Format: int64 */
            removed: number;
        };
        /** @description Every counter not attributable under a ?model= filter is null, never 0 (SPEC §4.1 "Null vs zero", §4.3 "Model-filtered requests"); not_attributable lists which ones. */
        Summary: {
            window: components["schemas"]["Window"];
            /** Format: int64 */
            sessions: number | null;
            /** Format: int64 */
            turns: number | null;
            /** Format: int64 */
            api_requests: number;
            /** Format: int64 */
            api_errors: number;
            tool_calls: number | null;
            tool_rejects: number | null;
            reject_rate: number | null;
            tokens: components["schemas"]["TokenUsage"];
            cost: components["schemas"]["Cost"];
            loc: components["schemas"]["LOC"] | null;
            /** Format: int64 */
            active_seconds: number | null;
            source: components["schemas"]["AnalyticsSourceValue"];
            metrics_only_projects: string[];
            not_attributable: string[];
        };
        SeriesPoint: {
            key: string;
            values: number[];
        };
        SeriesOther: {
            values: number[];
        };
        Series: {
            /** @enum {string} */
            bucket: "hour" | "day";
            buckets: string[];
            series: components["schemas"]["SeriesPoint"][];
            other?: components["schemas"]["SeriesOther"];
        };
        BreakdownRow: {
            /** @description Raw dimension value (tool/model name, or an unconstrained vocabulary like decision_source/query_source). */
            key: string;
            value: number;
            share: number;
        };
        Breakdown: {
            dimension: string;
            rows: components["schemas"]["BreakdownRow"][];
        };
        DecisionMatrixRow: {
            tool_name: string;
            /** Format: int64 */
            accept: number;
            /** Format: int64 */
            reject: number;
            /** @description Keys are raw decision_source values, unconstrained (SPEC §1.9). */
            by_source: {
                [key: string]: number;
            };
            exact_share: number;
            /** Format: int64 */
            p50_wait_ms: number | null;
            /** Format: int64 */
            p95_wait_ms: number | null;
        };
        DecisionMatrix: {
            rows: components["schemas"]["DecisionMatrixRow"][];
        };
        Facets: {
            projects: string[];
            models: string[];
            vendors: string[];
            tools: string[];
            decision_sources: string[];
            query_sources: string[];
        };
        DataQuality: {
            logs_exporter_seen: boolean;
            metrics_exporter_seen: boolean;
            hooks_seen: boolean;
            tool_details_seen: boolean;
        };
        /** @description SPEC §4.3 full shape. The live handler (server/internal/httpapi/meta.go) currently returns only {version, commit, retention_days} — P3-08 extends it to this full contract. */
        Meta: {
            version: string;
            commit: string;
            retention_days: number;
            feature_flags: {
                [key: string]: boolean;
            };
            vendors: string[];
            logs_exporter_seen: boolean;
            metrics_exporter_seen: boolean;
            hooks_seen: boolean;
            tool_details_seen: boolean;
            estimated_cost_present: boolean;
            data_quality: components["schemas"]["DataQuality"];
        };
        UnknownKindGroup: {
            event_name: string;
            source: components["schemas"]["EventSource"];
            /** Format: int64 */
            count: number;
            /** Format: date-time */
            first_seen: string;
            /** Format: date-time */
            last_seen: string;
            sample: {
                [key: string]: unknown;
            };
        };
        QualityUnknownKindsResponse: {
            rows: components["schemas"]["UnknownKindGroup"][];
        };
        HookLatencyRow: {
            hook_event: string;
            /** Format: int64 */
            executions: number;
            /** Format: int64 */
            p50_ms: number;
            /** Format: int64 */
            p95_ms: number;
            /** Format: int64 */
            p99_ms: number;
            /** Format: int64 */
            errors: number;
            /** Format: int64 */
            cancelled: number;
        };
        QualityHookLatencyResponse: {
            rows: components["schemas"]["HookLatencyRow"][];
        };
        /** @description event: event — a persisted event, slim shape (SPEC §5.1). Carries `id:` (the event_ref) on the SSE frame. */
        StreamEventFrame: components["schemas"]["TimelineEvent"];
        /** @description event: session — debounced (500ms/session) projection snapshot (SPEC §5.1). No `id:` line. */
        StreamSessionFrame: {
            id: string;
            status: components["schemas"]["SessionStatus"];
            turn_count: number;
            cost: components["schemas"]["SessionCost"];
        };
        /** @description event: stats — pipeline health, every 2s (SPEC §5.1). No `id:` line. */
        StreamStatsFrame: {
            events_per_sec: number;
            active_sessions: number;
            queue_depth: number;
            ingest_lag_ms: number;
            dropped_total: number;
        };
        /** @description event: lag — a subscriber's buffer overflowed (SPEC §5.1). No `id:` line. */
        StreamLagFrame: {
            dropped: number;
        };
        /** @description event: reset — the requested replay position predates the window (SPEC §5.1, §5.2). No `id:` line. */
        StreamResetFrame: {
            /** @enum {string} */
            reason: "replay_window_exceeded";
            /** Format: date-time */
            from: string;
        };
        /** @description event: shutdown — sent once on graceful shutdown so the browser reconnects instead of erroring (SPEC §5.1). No payload fields; body is an empty JSON object. */
        StreamShutdownFrame: Record<string, never>;
        /** @description The union of SSE frame payload shapes (SPEC §5.1). The frame *type* is carried by the SSE `event:` line, not a discriminator field in the JSON body — a client picks the right member by the frame's event name. */
        StreamEvent: components["schemas"]["StreamEventFrame"] | components["schemas"]["StreamSessionFrame"] | components["schemas"]["StreamStatsFrame"] | components["schemas"]["StreamLagFrame"] | components["schemas"]["StreamResetFrame"] | components["schemas"]["StreamShutdownFrame"];
    };
    responses: {
        /** @description Malformed or out-of-range request parameter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token (ARGUS_API_TOKEN configured). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Method not allowed on this resource. */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        SessionID: string;
        /** @description Default 50, max 500 (SPEC §4.1). */
        Limit: number;
        /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
        Cursor: string;
        /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
        From: string;
        /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
        To: string;
        /** @description Repeated params OR within the field (SPEC §4.1). */
        Project: string[];
        /** @description Repeated params OR within the field (SPEC §4.1). */
        Model: string[];
        /** @description Repeated params OR within the field (SPEC §4.1). */
        Vendor: string[];
        /** @description Repeated params OR within the field (SPEC §4.1). */
        Tool: string[];
        /** @description Repeated params OR within the field (SPEC §4.1). */
        DecisionSource: string[];
        /** @description Repeated params OR within the field (SPEC §4.1). Argus's own closed Kind taxonomy. */
        Kinds: components["schemas"]["Kind"][];
        PromptID: string;
        AgentID: string;
        Order: "asc" | "desc";
        /** @description slim (default, no attrs) or full. */
        Fields: "slim" | "full";
        /** @description Alternative to the Last-Event-ID header for SSE reconnect (SPEC §5.2). */
        After: string;
        /** @description SSE reconnect position, an opaque event_ref (SPEC §5.2). */
        LastEventIDHeader: string;
        /** @description ETag from a previous response; a match returns 304 with an empty body. */
        IfNoneMatch: string;
        /** @description Which source table to aggregate from. Argus-invented toggle, not vendor vocabulary: source='event' and source='metric' rows are never summed together (SPEC §2.4). */
        AnalyticsSource: "event" | "metric";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKStatus"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Not ready (draining, DB unreachable, migrations pending, or queue saturated). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getFacets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct raw values seen so far, per filterable dimension. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                model?: components["parameters"]["Model"];
                /** @description Repeated params OR (SPEC §4.1). */
                status?: components["schemas"]["SessionStatus"][];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                tool?: components["parameters"]["Tool"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                decision_source?: components["parameters"]["DecisionSource"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Substring match on id/project/cwd. */
                q?: string;
                sort?: "last_event_at" | "started_at" | "cost_usd" | "event_count";
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag from a previous response; a match returns 304 with an empty body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session, plus permission history, top tools, and decision summary. */
            200: {
                headers: {
                    /** @description Hash of the underlying max(ts, seq) + filter (SPEC §4.1). */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Not modified — the client's If-None-Match matches the current ETag. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getSessionTimeline: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). Argus's own closed Kind taxonomy. */
                kinds?: components["parameters"]["Kinds"];
                prompt_id?: components["parameters"]["PromptID"];
                agent_id?: components["parameters"]["AgentID"];
                order?: components["parameters"]["Order"];
                /** @description Reserved: accepted and currently ignored by the server. SPEC §4.3 lists it on this endpoint, but collapsing repeated events into groups is a presentation concern the UI performs client-side (PLAN P4-04's collapseEvents), and SPEC defines no server-side semantics for it. Documented as a no-op rather than silently accepted, so no client mistakes it for a filter that changes the result set. */
                collapse?: boolean;
                /** @description slim (default, no attrs) or full. */
                fields?: components["parameters"]["Fields"];
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of timeline events, ordered by (ts, vendor_seq, seq). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    listSessionTurns: {
        parameters: {
            query?: {
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of turns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnsListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    listSessionToolCalls: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). */
                tool?: components["parameters"]["Tool"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                decision_source?: components["parameters"]["DecisionSource"];
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tool calls. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallsListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getSessionSubagents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assembled subagent tree(s), depth-capped at 16. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubagentTree"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    streamSession: {
        parameters: {
            query?: {
                /** @description Alternative to the Last-Event-ID header for SSE reconnect (SPEC §5.2). */
                after?: components["parameters"]["After"];
            };
            header?: {
                /** @description SSE reconnect position, an opaque event_ref (SPEC §5.2). */
                "Last-Event-ID"?: components["parameters"]["LastEventIDHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of StreamEvent frames (SPEC §5.1): event, session, stats, lag, reset, shutdown, plus `: heartbeat` comments. Frame type is carried by the SSE `event:` line, not a field in the JSON body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). Argus's own closed Kind taxonomy. */
                kinds?: components["parameters"]["Kinds"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                tool?: components["parameters"]["Tool"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                decision_source?: components["parameters"]["DecisionSource"];
                prompt_id?: components["parameters"]["PromptID"];
                agent_id?: components["parameters"]["AgentID"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                order?: components["parameters"]["Order"];
                /** @description slim (default, no attrs) or full. */
                fields?: components["parameters"]["Fields"];
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events across sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque event_ref (base64url of ts+seq, SPEC §4.1). Not a lookup by id. */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event, with attrs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Malformed event_ref. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    listToolCalls: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                tool?: components["parameters"]["Tool"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                decision_source?: components["parameters"]["DecisionSource"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Default 50, max 500 (SPEC §4.1). */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from a previous page's page.next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tool calls across sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallsListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getAnalyticsSummary: {
        parameters: {
            query?: {
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                model?: components["parameters"]["Model"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description Which source table to aggregate from. Argus-invented toggle, not vendor vocabulary: source='event' and source='metric' rows are never summed together (SPEC §2.4). */
                source?: components["parameters"]["AnalyticsSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet-level KPIs for the window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getAnalyticsTimeseries: {
        parameters: {
            query: {
                metric: components["schemas"]["TimeseriesMetric"];
                /** @description Defaults to hour for windows <= 7 days, day beyond. */
                bucket?: "hour" | "day";
                group_by?: "project" | "model" | "vendor" | "none";
                limit_series?: number;
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                model?: components["parameters"]["Model"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description Which source table to aggregate from. Argus-invented toggle, not vendor vocabulary: source='event' and source='metric' rows are never summed together (SPEC §2.4). */
                source?: components["parameters"]["AnalyticsSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dense, zero-filled bucketed series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Invalid metric/bucket, or a non-attributable metric under a model filter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getAnalyticsBreakdown: {
        parameters: {
            query: {
                dimension: "model" | "project" | "tool" | "decision_source" | "query_source" | "error_type";
                metric?: "cost" | "calls" | "tokens";
                limit?: number;
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                model?: components["parameters"]["Model"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description Which source table to aggregate from. Argus-invented toggle, not vendor vocabulary: source='event' and source='metric' rows are never summed together (SPEC §2.4). */
                source?: components["parameters"]["AnalyticsSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top-N rows by the requested dimension. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getAnalyticsDecisions: {
        parameters: {
            query?: {
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision-provenance matrix. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionMatrix"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getQualityUnknownKinds: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unmapped event_name groups within the window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityUnknownKindsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getQualityHookLatency: {
        parameters: {
            query?: {
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339 timestamp or relative shorthand (-24h, -7d). SPEC §4.1. */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hook latency percentiles per hook_event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityHookLatencyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    streamAll: {
        parameters: {
            query?: {
                /** @description Repeated params OR within the field (SPEC §4.1). Argus's own closed Kind taxonomy. */
                kinds?: components["parameters"]["Kinds"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                project?: components["parameters"]["Project"];
                /** @description Repeated params OR within the field (SPEC §4.1). */
                vendor?: components["parameters"]["Vendor"];
                /** @description Alternative to the Last-Event-ID header for SSE reconnect (SPEC §5.2). */
                after?: components["parameters"]["After"];
            };
            header?: {
                /** @description SSE reconnect position, an opaque event_ref (SPEC §5.2). */
                "Last-Event-ID"?: components["parameters"]["LastEventIDHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of StreamEvent frames (SPEC §5.1), filtered by kinds/project/vendor, plus session projection and stats frames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    ingestLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted (OTLP ExportLogsServiceResponse; empty JSON object on success). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    ingestMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted (OTLP ExportMetricsServiceResponse; empty JSON object on success). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    ingestTraces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted (OTLP ExportTraceServiceResponse; empty JSON object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    ingestHook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted for asynchronous ingestion. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAck"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
}
