-- 002_events.sql
--
-- Reproduces docs/SPEC.md §2.2 verbatim. Two invariants are load-bearing and
-- must never be "fixed" by a future edit:
--
--   1. `UNIQUE (ts, dedup_key)` is declared on the PARENT table, not per
--      partition. A per-partition unique index does not satisfy
--      `INSERT ... ON CONFLICT (ts, dedup_key)` — reproduced on PG 18.4 with
--      "there is no unique or exclusion constraint matching the ON CONFLICT
--      specification". The parent-level constraint is legal because it
--      contains the partition key (ts), and Postgres auto-creates the
--      per-partition index (events_YYYY_MM_ts_dedup_key_key) on each
--      partition created under it — the partition manager (partitions.go)
--      must NOT create this index again.
--   2. There is NO DEFAULT partition. An insert whose `ts` falls outside
--      every existing partition's range must error, not silently land in a
--      catch-all — that error is how §1.7 rule 3's `too_old` classification
--      exists at all.
--
-- §0's rule applies here too: no CHECK constraint, enum, or domain on any
-- vendor-supplied vocabulary column (decision, decision_source,
-- tool_source, query_source, model, error_type, agent_type,
-- permission_mode, ...). The inline comments below are documentation only.

-- +goose Up
CREATE TABLE events (
    seq                   bigint GENERATED BY DEFAULT AS IDENTITY,
    id                    uuid NOT NULL DEFAULT uuidv7(),
    ts                    timestamptz NOT NULL,
    ingested_at           timestamptz NOT NULL DEFAULT now(),
    session_id            text NOT NULL,
    prompt_id             text,
    vendor                text NOT NULL,
    source                text NOT NULL,
    kind                  text NOT NULL,
    event_name            text NOT NULL,        -- unprefixed (SPEC §1.5.1)
    vendor_seq            bigint,
    tool_name             text,
    tool_use_id           text,
    decision              text,
    decision_source       text,
    tool_source           text,
    query_source          text,                 -- unconstrained (SPEC §1.9)
    model                 text,
    input_tokens          bigint,
    output_tokens         bigint,
    cache_read_tokens     bigint,
    cache_creation_tokens bigint,
    cost_usd              numeric(16,8),
    cost_source           text,
    duration_ms           integer,
    success               boolean,
    error_type            text,
    agent_id              text,
    parent_agent_id       text,
    agent_type            text,
    permission_mode       text,
    file_path             text,
    request_id            text,
    message_uuid          text,
    clock_skewed          boolean NOT NULL DEFAULT false,
    dedup_key             text NOT NULL,
    attrs                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (ts, seq),
    UNIQUE (ts, dedup_key)        -- MUST be on the parent: see the file header. Postgres creates
                                  -- the per-partition indexes automatically.
) PARTITION BY RANGE (ts);

-- +goose Down
DROP TABLE events;
