// Generated by `pnpm gen:fixtures` — do not edit.
// Source: server/api/openapi.yaml's response examples (PLAN.md P4-01).
// Regenerate with `pnpm gen:fixtures` after editing openapi.yaml.

import type { components, paths } from '@/api/schema'

export const healthz200Ok = {
  status: "ok",
} satisfies components['schemas']['OKStatus']

export const readyz200Ready = {
  status: "ok",
  migrations: "current",
} satisfies components['schemas']['ReadyStatus']

export const readyz503NotReady = {
  type: "urn:argus:error:not-ready",
  title: "Service Unavailable",
  status: 503,
  detail: "database health check failed: dial tcp: connection refused",
  instance: "/readyz",
} satisfies components['schemas']['Problem']

export const getMeta200Default = {
  version: "1.4.0",
  commit: "a1b2c3d",
  retention_days: 90,
  feature_flags: {},
  vendors: [
    "claude_code",
    "codex",
  ],
  logs_exporter_seen: true,
  metrics_exporter_seen: true,
  hooks_seen: true,
  tool_details_seen: false,
  estimated_cost_present: false,
  data_quality: {
    logs_exporter_seen: true,
    metrics_exporter_seen: true,
    hooks_seen: true,
    tool_details_seen: false,
  },
} satisfies components['schemas']['Meta']

export const getFacets200Default = {
  projects: [
    "argus",
    "platform",
  ],
  models: [
    "claude-opus-5",
    "claude-sonnet-4-5",
  ],
  vendors: [
    "claude_code",
    "codex",
  ],
  tools: [
    "Edit",
    "Read",
    "Bash",
  ],
  decision_sources: [
    "config",
    "hook",
    "user_permanent",
    "user_temporary",
    "user_reject",
    "user_abort",
  ],
  query_sources: [
    "",
    "sdk",
    "generate_session_title",
  ],
} satisfies components['schemas']['Facets']

export const listSessions200Default = {
  data: [
    {
      id: "3f7a3b1e-0000-0000-0000-000000000001",
      vendor: "claude_code",
      project: "argus",
      cwd: "/home/y/Labs/argus",
      status: "active",
      start_type: "fresh",
      started_at: "2026-08-11T09:02:11.412Z",
      ended_at: null,
      last_event_at: "2026-08-11T09:31:44.900Z",
      duration_ms: 1773488,
      turn_count: 12,
      event_count: 480,
      tool_call_count: 96,
      tool_reject_count: 3,
      subagent_count: 2,
      error_count: 1,
      tokens: {
        input: 41233,
        output: 18944,
        cache_read: 1204331,
        cache_creation: 88210,
      },
      cost: {
        usd: 4.2711,
        reported_usd: 4.2711,
        estimated_usd: 0,
        estimated_share: 0,
        by_query_source: {
          "": 3.9011,
          sdk: 0.35,
          generate_session_title: 0.02,
        },
        dominant_query_source: "",
        other_query_source_usd: 0.37,
      },
      models: [
        "claude-opus-5",
        "claude-sonnet-4-5",
      ],
      partial: false,
      app_version: "2.1.220",
      entrypoint: "cli",
      terminal_type: "wsl-Ubuntu",
    },
  ],
  page: {
    next_cursor: "eyJrIjoi4oCm",
    has_more: true,
  },
} satisfies components['schemas']['SessionsListResponse']

export const getSession200Default = {
  id: "3f7a3b1e-0000-0000-0000-000000000001",
  vendor: "claude_code",
  project: "argus",
  cwd: "/home/y/Labs/argus",
  status: "active",
  start_type: "fresh",
  started_at: "2026-08-11T09:02:11.412Z",
  ended_at: null,
  last_event_at: "2026-08-11T09:31:44.900Z",
  duration_ms: 1773488,
  turn_count: 12,
  event_count: 480,
  tool_call_count: 96,
  tool_reject_count: 3,
  subagent_count: 2,
  error_count: 1,
  tokens: {
    input: 41233,
    output: 18944,
    cache_read: 1204331,
    cache_creation: 88210,
  },
  cost: {
    usd: 4.2711,
    reported_usd: 4.2711,
    estimated_usd: 0,
    estimated_share: 0,
    by_query_source: {
      "": 3.9011,
      sdk: 0.35,
    },
    dominant_query_source: "",
    other_query_source_usd: 0.35,
  },
  models: [
    "claude-opus-5",
  ],
  partial: false,
  app_version: "2.1.220",
  entrypoint: "cli",
  terminal_type: "wsl-Ubuntu",
  permission_mode_history: [
    {
      ts: "2026-08-11T09:05:00.000Z",
      from: "default",
      to: "acceptEdits",
      trigger: "user",
    },
  ],
  top_tools: [
    {
      tool_name: "Edit",
      calls: 40,
      rejects: 2,
      p50_ms: 120,
    },
  ],
  decision_summary: {
    accept: 90,
    reject: 6,
    by_source: {
      config: 60,
      hook: 10,
      user_permanent: 10,
      user_temporary: 5,
      user_reject: 4,
      user_abort: 1,
    },
    exact_share: 1,
  },
  sources_seen: [
    "otel_log",
    "hook",
  ],
  raw_events_expired: false,
  hook_latency: {
    p50_ms: 9,
    p95_ms: 41,
    by_hook_event: {
      PostToolUse: 9,
    },
  },
  first_seen_at: "2026-08-11T09:02:10.000Z",
  user: "yohann",
  organization_id: "org_1",
} satisfies components['schemas']['SessionDetail']

export const getSessionTimeline200Default = {
  data: [
    {
      event_ref: "MTc2ODk2NzMyNDIyMTAwMDAwMDo5MTgyMzM",
      seq: 918233,
      id: "0192abcd-0000-0000-0000-000000000001",
      ts: "2026-08-11T09:12:04.221Z",
      session_id: "3f7a3b1e-0000-0000-0000-000000000001",
      prompt_id: "p_88f1",
      kind: "tool.decision",
      event_name: "tool_decision",
      source: "otel_log",
      vendor: "claude_code",
      tool_name: "Edit",
      tool_use_id: "toolu_01A",
      decision: "reject",
      decision_source: "user_reject",
      tool_source: "builtin",
      query_source: null,
      model: null,
      tokens: null,
      cost: null,
      duration_ms: null,
      success: null,
      error_type: null,
      agent_id: null,
      agent_type: null,
      permission_mode: "default",
      file_path: "server/internal/store/postgres/store.go",
      clock_skewed: false,
    },
  ],
  page: {
    next_cursor: null,
    has_more: false,
  },
} satisfies components['schemas']['TimelineListResponse']

export const listSessionTurns200Default = {
  data: [
    {
      session_id: "3f7a3b1e-0000-0000-0000-000000000001",
      prompt_id: "p_88f1",
      turn_index: 3,
      started_at: "2026-08-11T09:11:00.000Z",
      ended_at: "2026-08-11T09:12:30.000Z",
      first_seen_at: "2026-08-11T09:11:00.100Z",
      last_event_at: "2026-08-11T09:12:30.000Z",
      duration_ms: 90000,
      status: "complete",
      api_request_count: 2,
      tool_call_count: 5,
      tool_reject_count: 1,
      error_count: 0,
      input_tokens: 4123,
      output_tokens: 1894,
      cache_read_tokens: 12000,
      cache_creation_tokens: 800,
      cost_usd: 0.42,
      cost_estimated_usd: 0,
      models: [
        "claude-opus-5",
      ],
    },
  ],
  page: {
    next_cursor: null,
    has_more: false,
  },
} satisfies components['schemas']['TurnsListResponse']

export const listSessionToolCalls200Default = {
  data: [
    {
      id: "5b1f7a2e-0000-0000-0000-000000000001",
      session_id: "3f7a3b1e-0000-0000-0000-000000000001",
      prompt_id: "p_88f1",
      tool_use_id: "toolu_01A",
      tool_name: "Edit",
      tool_source: "builtin",
      agent_id: null,
      decision: "reject",
      decision_source: "user_reject",
      permission_mode: "default",
      started_at: "2026-08-11T09:12:04.000Z",
      decided_at: "2026-08-11T09:12:04.200Z",
      ended_at: "2026-08-11T09:12:04.200Z",
      duration_ms: 200,
      wait_ms: 200,
      success: false,
      error_type: null,
      file_path: "server/internal/store/postgres/store.go",
      input_size_bytes: 412,
      result_size_bytes: null,
      correlation: "exact",
      event_count: 2,
    },
  ],
  page: {
    next_cursor: null,
    has_more: false,
  },
} satisfies components['schemas']['ToolCallsListResponse']

export const getSessionSubagents200Default = {
  data: [
    {
      agent_id: "root",
      parent_agent_id: null,
      agent_type: "main",
      depth: 0,
      status: "running",
      started_at: "2026-08-11T09:02:11.412Z",
      ended_at: null,
      tool_call_count: 40,
      cost_usd: null,
      children: [
        {
          agent_id: "ag_7",
          parent_agent_id: "root",
          agent_type: "Explore",
          depth: 1,
          status: "complete",
          started_at: "2026-08-11T09:05:00.000Z",
          ended_at: "2026-08-11T09:08:00.000Z",
          spawn_tool_use_id: "toolu_9f",
          tool_call_count: 12,
          cost_usd: null,
          children: [],
        },
      ],
    },
  ],
  cost_attribution: {
    by_query_source: {
      "": 3.9011,
      sdk: 0.35,
    },
    dominant_query_source: "",
    other_query_source_usd: 0.35,
    per_node_available: false,
    note: "Claude Code does not emit per-agent cost; api_request carries query_source only.",
  },
} satisfies components['schemas']['SubagentTree']

export const listEvents200Default = {
  data: [
    {
      event_ref: "MTc2ODk2NzMyNDIyMTAwMDAwMDo5MTgyMzM",
      seq: 918233,
      id: "0192abcd-0000-0000-0000-000000000001",
      ts: "2026-08-11T09:12:04.221Z",
      session_id: "3f7a3b1e-0000-0000-0000-000000000001",
      prompt_id: "p_88f1",
      kind: "tool.decision",
      event_name: "tool_decision",
      source: "otel_log",
      vendor: "claude_code",
      tool_name: "Edit",
      tool_use_id: "toolu_01A",
      decision: "reject",
      decision_source: "user_reject",
      tool_source: "builtin",
      query_source: null,
      model: null,
      tokens: null,
      cost: null,
      duration_ms: null,
      success: null,
      error_type: null,
      agent_id: null,
      agent_type: null,
      permission_mode: "default",
      file_path: "server/internal/store/postgres/store.go",
      clock_skewed: false,
    },
  ],
  page: {
    next_cursor: null,
    has_more: false,
  },
} satisfies components['schemas']['TimelineListResponse']

export const getEvent200Default = {
  event_ref: "MTc2ODk2NzMyNDIyMTAwMDAwMDo5MTgyMzM",
  seq: 918233,
  id: "0192abcd-0000-0000-0000-000000000001",
  ts: "2026-08-11T09:12:04.221Z",
  session_id: "3f7a3b1e-0000-0000-0000-000000000001",
  prompt_id: "p_88f1",
  kind: "tool.decision",
  event_name: "tool_decision",
  source: "otel_log",
  vendor: "claude_code",
  tool_name: "Edit",
  tool_use_id: "toolu_01A",
  decision: "reject",
  decision_source: "user_reject",
  tool_source: "builtin",
  query_source: null,
  model: null,
  tokens: null,
  cost: null,
  duration_ms: null,
  success: null,
  error_type: null,
  agent_id: null,
  agent_type: null,
  permission_mode: "default",
  file_path: "server/internal/store/postgres/store.go",
  clock_skewed: false,
  attrs: {
    "tool_decision.tool_use_id": "toolu_01A",
    "tool_decision.decision": "reject",
  },
} satisfies components['schemas']['EventDetail']

export const getEvent400InvalidEventRef = {
  type: "urn:argus:error:invalid-event-ref",
  title: "Bad Request",
  status: 400,
  detail: "event_ref is not valid base64url of ts:seq",
  instance: "/api/v1/events/not-a-ref",
} satisfies components['schemas']['Problem']

export const listToolCalls200Default = {
  data: [
    {
      id: "5b1f7a2e-0000-0000-0000-000000000001",
      session_id: "3f7a3b1e-0000-0000-0000-000000000001",
      prompt_id: "p_88f1",
      tool_use_id: "toolu_01A",
      tool_name: "Edit",
      tool_source: "builtin",
      agent_id: null,
      decision: "reject",
      decision_source: "user_reject",
      permission_mode: "default",
      started_at: "2026-08-11T09:12:04.000Z",
      decided_at: "2026-08-11T09:12:04.200Z",
      ended_at: "2026-08-11T09:12:04.200Z",
      duration_ms: 200,
      wait_ms: 200,
      success: false,
      error_type: null,
      file_path: "server/internal/store/postgres/store.go",
      input_size_bytes: 412,
      result_size_bytes: null,
      correlation: "exact",
      event_count: 2,
    },
  ],
  page: {
    next_cursor: null,
    has_more: false,
  },
} satisfies components['schemas']['ToolCallsListResponse']

export const getAnalyticsSummary200Default = {
  window: {
    from: "2026-08-04T00:00:00Z",
    to: "2026-08-11T00:00:00Z",
    bucket: "hour",
  },
  sessions: 34,
  turns: 291,
  api_requests: 1044,
  api_errors: 7,
  tool_calls: 2210,
  tool_rejects: 91,
  reject_rate: 0.0412,
  tokens: {
    input: 1200000,
    output: 340000,
    cache_read: 81000000,
    cache_creation: 990000,
  },
  cost: {
    usd: 71.44,
    reported_usd: 70.02,
    estimated_usd: 1.42,
    estimated_share: 0.0199,
  },
  loc: {
    added: 8123,
    removed: 2044,
  },
  active_seconds: 41220,
  source: "event",
  metrics_only_projects: [
    "legacy-app",
  ],
  not_attributable: [],
} satisfies components['schemas']['Summary']

export const getAnalyticsSummary200ModelFiltered = {
  window: {
    from: "2026-08-04T00:00:00Z",
    to: "2026-08-11T00:00:00Z",
    bucket: "hour",
  },
  sessions: null,
  turns: null,
  api_requests: 512,
  api_errors: 3,
  tool_calls: null,
  tool_rejects: null,
  reject_rate: null,
  tokens: {
    input: 600000,
    output: 170000,
    cache_read: 40000000,
    cache_creation: 500000,
  },
  cost: {
    usd: 35.2,
    reported_usd: 35.2,
    estimated_usd: 0,
    estimated_share: 0,
  },
  loc: null,
  active_seconds: null,
  source: "event",
  metrics_only_projects: [],
  not_attributable: [
    "sessions",
    "turns",
    "tool_calls",
    "tool_rejects",
    "reject_rate",
    "loc",
    "active_seconds",
  ],
} satisfies components['schemas']['Summary']

export const getAnalyticsTimeseries200Default = {
  bucket: "hour",
  buckets: [
    "2026-08-11T08:00:00Z",
    "2026-08-11T09:00:00Z",
  ],
  series: [
    {
      key: "argus",
      values: [
        1.2,
        0,
      ],
    },
  ],
  other: {
    values: [
      0.4,
      0.1,
    ],
  },
} satisfies components['schemas']['Series']

export const getAnalyticsTimeseries400NotAttributable = {
  type: "urn:argus:error:not-attributable",
  title: "Bad Request",
  status: 400,
  detail: "metric=sessions is not attributable under a model filter",
  instance: "/api/v1/analytics/timeseries",
} satisfies components['schemas']['Problem']

export const getAnalyticsTimeseries400InvalidMetric = {
  type: "urn:argus:error:invalid-parameter",
  title: "Bad Request",
  status: 400,
  detail: "metric must be one of cost, tokens, sessions, turns, api_requests, api_errors, tool_calls, tool_rejects, loc",
  instance: "/api/v1/analytics/timeseries",
} satisfies components['schemas']['Problem']

export const getAnalyticsBreakdown200Default = {
  dimension: "tool",
  rows: [
    {
      key: "Edit",
      value: 812,
      share: 0.37,
    },
  ],
} satisfies components['schemas']['Breakdown']

export const getAnalyticsDecisions200Default = {
  rows: [
    {
      tool_name: "Edit",
      accept: 300,
      reject: 41,
      by_source: {
        config: 210,
        hook: 12,
        user_permanent: 40,
        user_temporary: 38,
        user_reject: 37,
        user_abort: 4,
      },
      exact_share: 1,
      p50_wait_ms: 1900,
      p95_wait_ms: 22400,
    },
  ],
} satisfies components['schemas']['DecisionMatrix']

export const getQualityUnknownKinds200Default = {
  rows: [
    {
      event_name: "some_new_event",
      source: "otel_log",
      count: 41,
      first_seen: "2026-08-10T10:00:00Z",
      last_seen: "2026-08-11T09:00:00Z",
      sample: {
        "raw.attr": "value",
      },
    },
  ],
} satisfies components['schemas']['QualityUnknownKindsResponse']

export const getQualityHookLatency200Default = {
  rows: [
    {
      hook_event: "PostToolUse",
      executions: 412,
      p50_ms: 9,
      p95_ms: 41,
      p99_ms: 120,
      errors: 0,
      cancelled: 0,
    },
  ],
} satisfies components['schemas']['QualityHookLatencyResponse']

export const ingestLogs200Default = {} satisfies paths['/v1/logs']['post']['responses']['200']['content']['application/json']

export const ingestMetrics200Default = {} satisfies paths['/v1/metrics']['post']['responses']['200']['content']['application/json']

export const ingestTraces200Default = {} satisfies paths['/v1/traces']['post']['responses']['200']['content']['application/json']

export const ingestHook202Default = {
  ok: true,
  event: "PostToolUse",
} satisfies components['schemas']['HookAccepted']

export const ingestHook413Default = {
  type: "urn:argus:error:payload-too-large",
  title: "Request Entity Too Large",
  status: 413,
  detail: "hook payload exceeds the configured ARGUS_INGEST_MAX_BODY_BYTES limit",
  instance: "/ingest/hook",
} satisfies components['schemas']['Problem']

export const ingestHook429Default = {
  type: "urn:argus:error:queue-full",
  title: "Too Many Requests",
  status: 429,
  detail: "ingest queue is full; hooks are not retried by Claude Code, so this request's events were dropped",
  instance: "/ingest/hook",
} satisfies components['schemas']['Problem']
