// read_events_test.go is a black-box (package postgres_test) integration
// suite for ListEvents/GetEvent (P3-03), following read_sessions_test.go's
// convention (external test package; seeding helpers insert directly via
// SQL for precise control over ts/vendor_seq/seq/attrs that the write path
// would be awkward to steer). Reuses newStore/ensureRange/nextTestSessionID
// from write_test.go/read_sessions_test.go rather than redefining them.
package postgres_test

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/require"

	"github.com/YohannHommet/argus/server/internal/model"
	"github.com/YohannHommet/argus/server/internal/store"
	"github.com/YohannHommet/argus/server/internal/store/postgres"
)

// eventSeed is the direct-SQL fixture seedFullEvent inserts. Seq is
// explicit (events.seq is GENERATED BY DEFAULT AS IDENTITY, so an explicit
// value is accepted) so tests can construct ts/vendor_seq/seq combinations
// the ordering ACs need without racing the identity sequence.
type eventSeed struct {
	Seq            int64
	SessionID      string
	TS             time.Time
	Vendor         string
	Source         string
	Kind           string
	EventName      string
	VendorSeq      *int64
	ToolName       *string
	PromptID       *string
	AgentID        *string
	DecisionSource *string
	DedupKey       string
	Attrs          map[string]any
}

// seedFullEventsBulk inserts many eventSeed rows in one statement (via
// unnest), for tests that need enough rows for the planner to prefer an
// index over a sequential scan (SPEC §2.5's EXPLAIN ACs) without paying one
// round trip per row.
func seedFullEventsBulk(t *testing.T, pool *pgxpool.Pool, seeds []eventSeed) {
	t.Helper()
	n := len(seeds)
	seqs := make([]int64, n)
	sessionIDs := make([]string, n)
	tsVals := make([]time.Time, n)
	vendors := make([]string, n)
	sources := make([]string, n)
	kinds := make([]string, n)
	eventNames := make([]string, n)
	vendorSeqs := make([]*int64, n)
	toolNames := make([]*string, n)
	promptIDs := make([]*string, n)
	agentIDs := make([]*string, n)
	decisionSources := make([]*string, n)
	dedupKeys := make([]string, n)
	attrsJSON := make([]string, n)
	for i, seed := range seeds {
		if seed.Vendor == "" {
			seed.Vendor = "claude_code"
		}
		if seed.Source == "" {
			seed.Source = "otel_log"
		}
		if seed.EventName == "" {
			seed.EventName = seed.Kind
		}
		if seed.DedupKey == "" {
			seed.DedupKey = fmt.Sprintf("dedup-%d", seed.Seq)
		}
		b, err := json.Marshal(seed.Attrs)
		require.NoError(t, err)

		seqs[i] = seed.Seq
		sessionIDs[i] = seed.SessionID
		tsVals[i] = seed.TS
		vendors[i] = seed.Vendor
		sources[i] = seed.Source
		kinds[i] = seed.Kind
		eventNames[i] = seed.EventName
		vendorSeqs[i] = seed.VendorSeq
		toolNames[i] = seed.ToolName
		promptIDs[i] = seed.PromptID
		agentIDs[i] = seed.AgentID
		decisionSources[i] = seed.DecisionSource
		dedupKeys[i] = seed.DedupKey
		attrsJSON[i] = string(b)
	}

	_, err := pool.Exec(context.Background(), `
		INSERT INTO events (seq, session_id, ts, vendor, source, kind, event_name, vendor_seq,
		                     tool_name, prompt_id, agent_id, decision_source, dedup_key, attrs)
		SELECT * FROM unnest(
			$1::bigint[], $2::text[], $3::timestamptz[], $4::text[], $5::text[], $6::text[], $7::text[],
			$8::bigint[], $9::text[], $10::text[], $11::text[], $12::text[], $13::text[], $14::jsonb[])`,
		seqs, sessionIDs, tsVals, vendors, sources, kinds, eventNames, vendorSeqs,
		toolNames, promptIDs, agentIDs, decisionSources, dedupKeys, attrsJSON,
	)
	require.NoError(t, err)
}

func seedFullEvent(t *testing.T, pool *pgxpool.Pool, seed eventSeed) {
	t.Helper()
	if seed.Vendor == "" {
		seed.Vendor = "claude_code"
	}
	if seed.Source == "" {
		seed.Source = "otel_log"
	}
	if seed.EventName == "" {
		seed.EventName = seed.Kind
	}
	if seed.DedupKey == "" {
		seed.DedupKey = fmt.Sprintf("dedup-%d", seed.Seq)
	}
	attrsJSON, err := json.Marshal(seed.Attrs)
	require.NoError(t, err)

	_, err = pool.Exec(context.Background(), `
		INSERT INTO events (seq, session_id, ts, vendor, source, kind, event_name, vendor_seq,
		                     tool_name, prompt_id, agent_id, decision_source, dedup_key, attrs)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,
		seed.Seq, seed.SessionID, seed.TS, seed.Vendor, seed.Source, seed.Kind, seed.EventName, seed.VendorSeq,
		seed.ToolName, seed.PromptID, seed.AgentID, seed.DecisionSource, seed.DedupKey, attrsJSON,
	)
	require.NoError(t, err)
}

// --- ordering ACs ---------------------------------------------------------

func TestListEvents_IdenticalTS_OrdersByVendorSeqNotSeq(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("tie")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base)

	// seq is HIGHER for the row whose vendor_seq is LOWER: a (ts, seq)-only
	// keyset/sort would get this backwards (SPEC §1.2's "ordering is exactly
	// (ts, vendor_seq NULLS LAST, seq)" AC).
	seedFullEvent(t, pool, eventSeed{Seq: 1001, SessionID: sessionID, TS: base, Kind: "tool.decision", VendorSeq: ptrInt64(5)})
	seedFullEvent(t, pool, eventSeed{Seq: 1002, SessionID: sessionID, TS: base, Kind: "tool.decision", VendorSeq: ptrInt64(3)})

	got, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID}, store.Page{Limit: 10})
	require.NoError(t, err)
	require.Len(t, got, 2)
	require.Equal(t, int64(1002), got[0].Seq, "vendor_seq=3 must come first even though its seq (1002) is larger")
	require.Equal(t, int64(1001), got[1].Seq)
}

func TestListEvents_VendorSeqNullsLast(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("nulls")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base)

	seedFullEvent(t, pool, eventSeed{Seq: 2001, SessionID: sessionID, TS: base, Kind: "tool.decision", VendorSeq: nil})
	seedFullEvent(t, pool, eventSeed{Seq: 2002, SessionID: sessionID, TS: base, Kind: "tool.decision", VendorSeq: ptrInt64(1)})

	got, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID}, store.Page{Limit: 10})
	require.NoError(t, err)
	require.Len(t, got, 2)
	require.Equal(t, int64(2002), got[0].Seq, "a real vendor_seq sorts before a NULL one (NULLS LAST)")
	require.Equal(t, int64(2001), got[1].Seq)
}

func TestListEvents_OrderDescIsExactReverseOfAsc(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("reverse")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base.Add(time.Hour))

	seedFullEvent(t, pool, eventSeed{Seq: 3001, SessionID: sessionID, TS: base, Kind: "tool.pre", VendorSeq: ptrInt64(2)})
	seedFullEvent(t, pool, eventSeed{Seq: 3002, SessionID: sessionID, TS: base, Kind: "tool.pre", VendorSeq: nil})
	seedFullEvent(t, pool, eventSeed{Seq: 3003, SessionID: sessionID, TS: base.Add(time.Second), Kind: "tool.pre", VendorSeq: ptrInt64(1)})
	seedFullEvent(t, pool, eventSeed{Seq: 3004, SessionID: sessionID, TS: base.Add(2 * time.Second), Kind: "tool.pre", VendorSeq: nil})

	asc, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Order: store.OrderAsc}, store.Page{Limit: 10})
	require.NoError(t, err)
	desc, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Order: store.OrderDesc}, store.Page{Limit: 10})
	require.NoError(t, err)

	require.Len(t, asc, 4)
	require.Len(t, desc, 4)
	for i := range asc {
		require.Equalf(t, asc[i].Seq, desc[len(desc)-1-i].Seq, "desc must be the exact reverse of asc at position %d", i)
	}
}

// --- fields=slim|full ------------------------------------------------------

func TestListEvents_FieldsSlimOmitsAttrs_MeasurablySmaller(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("fields")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base)

	bigAttrs := map[string]any{
		"tool_input":  "a moderately long string that would not appear in the slim response at all",
		"nested":      map[string]any{"a": 1, "b": 2, "c": []int{1, 2, 3, 4, 5}},
		"another_key": "more padding to make the size difference unambiguous",
	}
	seedFullEvent(t, pool, eventSeed{Seq: 4001, SessionID: sessionID, TS: base, Kind: "tool.result", Attrs: bigAttrs})

	slim, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Fields: store.FieldsSlim}, store.Page{Limit: 10})
	require.NoError(t, err)
	full, _, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Fields: store.FieldsFull}, store.Page{Limit: 10})
	require.NoError(t, err)
	require.Len(t, slim, 1)
	require.Len(t, full, 1)

	require.Nil(t, slim[0].Attrs, "fields=slim must not select attrs from the database at all")
	require.Equal(t, "a moderately long string that would not appear in the slim response at all", full[0].Attrs["tool_input"])

	slimJSON, err := json.Marshal(slim[0])
	require.NoError(t, err)
	fullJSON, err := json.Marshal(full[0])
	require.NoError(t, err)
	require.Greaterf(t, len(fullJSON), len(slimJSON), "full JSON (%d bytes) must be measurably larger than slim (%d bytes)", len(fullJSON), len(slimJSON))
}

// --- cross-partition keyset pagination -------------------------------------

func TestListEvents_KeysetAcrossPartitionBoundary_EveryRowExactlyOnce(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("xpart")
	seedSession(t, pool, sessionSeed{ID: sessionID})

	monthA := time.Date(2025, 6, 1, 0, 0, 0, 0, time.UTC)
	monthB := time.Date(2025, 7, 1, 0, 0, 0, 0, time.UTC)
	require.NoError(t, st.EnsurePartitions(context.Background(), monthA, monthB))

	const perMonth = 15
	expected := map[int64]struct{}{}
	seq := int64(5000)
	for i := 0; i < perMonth; i++ {
		seq++
		ts := monthA.Add(time.Duration(i) * time.Hour)
		seedFullEvent(t, pool, eventSeed{Seq: seq, SessionID: sessionID, TS: ts, Kind: "tool.pre", VendorSeq: ptrInt64(int64(i))})
		expected[seq] = struct{}{}
	}
	for i := 0; i < perMonth; i++ {
		seq++
		ts := monthB.Add(time.Duration(i) * time.Hour)
		seedFullEvent(t, pool, eventSeed{Seq: seq, SessionID: sessionID, TS: ts, Kind: "tool.pre", VendorSeq: ptrInt64(int64(i))})
		expected[seq] = struct{}{}
	}

	seen := map[int64]int{}
	var cursor store.Cursor
	pages := 0
	for {
		pages++
		require.Lessf(t, pages, 20, "too many pages — pagination is likely looping")
		got, next, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID}, store.Page{Limit: 4, Cursor: cursor})
		require.NoError(t, err)
		for _, e := range got {
			seen[e.Seq]++
		}
		if next == "" {
			break
		}
		cursor = next
	}

	require.Len(t, seen, len(expected), "every seeded row must be returned")
	for seqVal := range expected {
		require.Equalf(t, 1, seen[seqVal], "seq %d must be returned exactly once, got %d", seqVal, seen[seqVal])
	}
}

// --- GetEvent ---------------------------------------------------------------

func TestGetEvent_NotFound(t *testing.T) {
	st, _ := newStore(t)
	_, err := st.GetEvent(context.Background(), model.EventRef{TS: time.Now().UTC(), Seq: 999999})
	require.ErrorIs(t, err, postgres.ErrEventNotFound)
}

func TestGetEvent_ReturnsRowWithAttrs(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("getevent")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	ts := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, ts, ts)

	attrs := map[string]any{"tool_decision.tool_use_id": "toolu_01A", "tool_decision.decision": "reject"}
	seedFullEvent(t, pool, eventSeed{
		Seq: 6001, SessionID: sessionID, TS: ts, Kind: "tool.decision",
		ToolName: ptrString("Edit"), DecisionSource: ptrString("user_reject"), Attrs: attrs,
	})

	got, err := st.GetEvent(context.Background(), model.EventRef{TS: ts, Seq: 6001})
	require.NoError(t, err)
	require.Equal(t, int64(6001), got.Seq)
	require.Equal(t, sessionID, got.SessionID)
	require.Equal(t, "Edit", *got.ToolName)
	require.Equal(t, "user_reject", *got.DecisionSource)
	require.Equal(t, "reject", got.Attrs["tool_decision.decision"])
}

// TestGetEvent_IndexScanOnSinglePartition verifies SPEC §2.5's AC: GetEvent's
// (ts, seq) PK lookup shows an Index Scan touching exactly one partition
// (review M2: there is no events.id index, so a uuid lookup would have been
// a full scan of every partition). Asserted on EXPLAIN plan text per the
// ticket note (P3-02's equivalent AC used pg_stat_user_indexes deltas
// instead, but this AC explicitly names EXPLAIN and "one partition").
func TestGetEvent_IndexScanOnSinglePartition(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("explain-getevent")
	seedSession(t, pool, sessionSeed{ID: sessionID})

	months := []time.Time{
		time.Date(2025, 3, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2025, 4, 1, 0, 0, 0, 0, time.UTC),
		time.Date(2025, 5, 1, 0, 0, 0, 0, time.UTC),
	}
	require.NoError(t, st.EnsurePartitions(context.Background(), months[0], months[len(months)-1]))

	const perMonth = 4000
	seq := int64(7000)
	var targetTS time.Time
	var targetSeq int64
	var seeds []eventSeed
	for _, month := range months {
		for i := 0; i < perMonth; i++ {
			seq++
			ts := month.Add(time.Duration(i) * time.Second)
			seeds = append(seeds, eventSeed{Seq: seq, SessionID: sessionID, TS: ts, Kind: "tool.pre"})
			if month.Equal(months[1]) && i == perMonth/2 {
				targetTS, targetSeq = ts, seq
			}
		}
	}
	seedFullEventsBulk(t, pool, seeds)
	require.False(t, targetTS.IsZero(), "target row must have been seeded")
	_, err := pool.Exec(context.Background(), "ANALYZE events")
	require.NoError(t, err)

	rows, err := pool.Query(context.Background(),
		"EXPLAIN SELECT seq, id, ts FROM events WHERE ts = $1 AND seq = $2", targetTS, targetSeq)
	require.NoError(t, err)
	defer rows.Close()

	var planLines []string
	for rows.Next() {
		var line string
		require.NoError(t, rows.Scan(&line))
		planLines = append(planLines, line)
	}
	require.NoError(t, rows.Err())
	plan := fmt.Sprintf("%v", planLines)

	require.Contains(t, plan, "Index Scan", "GetEvent's (ts, seq) PK lookup must use an Index Scan, not a Seq Scan")

	expectedPartition := fmt.Sprintf("events_%04d_%02d", months[1].Year(), months[1].Month())
	require.Contains(t, plan, expectedPartition, "the plan must reference the single partition containing ts")
	for _, month := range []time.Time{months[0], months[2]} {
		other := fmt.Sprintf("events_%04d_%02d", month.Year(), month.Month())
		require.NotContainsf(t, plan, other, "partition pruning must exclude %s — only one partition should be touched", other)
	}
}

// TestListEvents_SessionTimeline_IndexScanWithPartitionPruning verifies SPEC
// §2.5's AC for the session timeline: an index scan on
// `events_*(session_id, ts, seq)` with partition pruning. Built from the
// exact filter/page ListEvents itself uses (store.EventFilter.SessionID),
// EXPLAINed directly rather than through the store method, since Store
// exposes no EXPLAIN hook.
func TestListEvents_SessionTimeline_IndexScanWithPartitionPruning(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("explain-timeline")
	seedSession(t, pool, sessionSeed{ID: sessionID})

	month := time.Date(2025, 9, 1, 0, 0, 0, 0, time.UTC)
	require.NoError(t, st.EnsurePartitions(context.Background(), month, month))

	// Many OTHER sessions interleave with `sessionID` at a realistic
	// fan-out (SPEC §2.4's partition holds every session active that
	// month): sessionID's rows are only 1/50th of the partition, sparse
	// and scattered through the whole ts range, so a full-partition scan
	// riding the (ts, seq) PK — cheap when a target session's share is
	// large enough that ts order alone gets you to LIMIT quickly — is no
	// longer the planner's best option; the selective (session_id, ts,
	// seq) index is.
	const n = 20000
	const fanOut = 50
	seq := int64(8000)
	var seeds []eventSeed
	for i := 0; i < n; i++ {
		seq++
		ts := month.Add(time.Duration(i) * time.Second)
		sid := sessionID
		if i%fanOut != 0 {
			sid = fmt.Sprintf("explain-timeline-other-%d", i%fanOut)
		}
		seeds = append(seeds, eventSeed{Seq: seq, SessionID: sid, TS: ts, Kind: "tool.pre", VendorSeq: ptrInt64(int64(i))})
	}
	seedFullEventsBulk(t, pool, seeds)
	_, err := pool.Exec(context.Background(), "ANALYZE events")
	require.NoError(t, err)

	explainSQL := "EXPLAIN SELECT e.seq FROM events e WHERE e.session_id = $1 ORDER BY e.ts ASC, e.vendor_seq ASC NULLS LAST, e.seq ASC LIMIT 51"
	rows, err := pool.Query(context.Background(), explainSQL, sessionID)
	require.NoError(t, err)
	defer rows.Close()

	var planLines []string
	for rows.Next() {
		var line string
		require.NoError(t, rows.Scan(&line))
		planLines = append(planLines, line)
	}
	require.NoError(t, rows.Err())
	plan := fmt.Sprintf("%v", planLines)

	require.Contains(t, plan, "Index Scan", "the session timeline must use an Index Scan")
	expectedIndex := fmt.Sprintf("events_%04d_%02d_session_ts_seq_idx", month.Year(), month.Month())
	require.Contains(t, plan, expectedIndex, "the session timeline must ride the (session_id, ts, seq) index")
}

// --- cursor codec (verified through the exported API only) ----------------

func TestListEvents_CursorRejectsWrongOrder(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("cursor-order")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base)
	for i := 0; i < 3; i++ {
		seedFullEvent(t, pool, eventSeed{Seq: 10100 + int64(i), SessionID: sessionID, TS: base.Add(time.Duration(i) * time.Second), Kind: "tool.pre"})
	}

	_, cursor, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Order: store.OrderAsc}, store.Page{Limit: 1})
	require.NoError(t, err)
	require.NotEmpty(t, cursor)

	_, _, err = st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Order: store.OrderDesc}, store.Page{Limit: 1, Cursor: cursor})
	require.Error(t, err)
	require.ErrorIs(t, err, postgres.ErrInvalidCursor, "a cursor minted under one order must be rejected when replayed against the other")
}

func TestListEvents_CursorTamperRejection(t *testing.T) {
	st, _ := newStore(t)
	_, _, err := st.ListEvents(context.Background(), store.EventFilter{}, store.Page{Limit: 1, Cursor: "not-a-valid-cursor!!"})
	require.Error(t, err)
	require.ErrorIs(t, err, postgres.ErrInvalidCursor)
}

func TestListEvents_KeysetPagination_DescOrder_ZeroDuplicatesZeroOmissions(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("desc-page")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Add(-time.Hour).Truncate(time.Millisecond)
	ensureRange(t, st, base, base.Add(time.Hour))

	const total = 21
	expected := map[int64]struct{}{}
	seq := int64(11000)
	var seeds []eventSeed
	for i := 0; i < total; i++ {
		seq++
		var vs *int64
		if i%2 == 0 {
			vs = ptrInt64(int64(i))
		}
		seeds = append(seeds, eventSeed{Seq: seq, SessionID: sessionID, TS: base.Add(time.Duration(i/3) * time.Second), Kind: "tool.pre", VendorSeq: vs})
		expected[seq] = struct{}{}
	}
	seedFullEventsBulk(t, pool, seeds)

	seen := map[int64]int{}
	var cursor store.Cursor
	pages := 0
	for {
		pages++
		require.Lessf(t, pages, 20, "too many pages — pagination is likely looping")
		got, next, err := st.ListEvents(context.Background(), store.EventFilter{SessionID: sessionID, Order: store.OrderDesc}, store.Page{Limit: 4, Cursor: cursor})
		require.NoError(t, err)
		for _, e := range got {
			seen[e.Seq]++
		}
		if next == "" {
			break
		}
		cursor = next
	}

	require.Len(t, seen, total)
	for seqVal := range expected {
		require.Equalf(t, 1, seen[seqVal], "seq %d must be returned exactly once, got %d", seqVal, seen[seqVal])
	}
}

// --- filter fields ----------------------------------------------------------

func TestListEvents_EveryFilterField(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("filters")
	otherSessionID := nextTestSessionID("filters-other")
	seedSession(t, pool, sessionSeed{ID: sessionID, Project: "argus"})
	seedSession(t, pool, sessionSeed{ID: otherSessionID, Project: "other-project"})
	base := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, base, base)

	match := eventSeed{
		Seq: 12001, SessionID: sessionID, TS: base, Kind: "tool.decision", EventName: "tool_decision",
		ToolName: ptrString("Edit"), PromptID: ptrString("p1"), AgentID: ptrString("root"),
		DecisionSource: ptrString("user_reject"), Vendor: "claude_code",
	}
	seedFullEvent(t, pool, match)
	// Distractors, each violating exactly one filter dimension.
	seedFullEvent(t, pool, eventSeed{Seq: 12002, SessionID: sessionID, TS: base, Kind: "tool.pre", ToolName: ptrString("Edit"), PromptID: ptrString("p1"), AgentID: ptrString("root"), DecisionSource: ptrString("user_reject")})
	seedFullEvent(t, pool, eventSeed{Seq: 12003, SessionID: sessionID, TS: base, Kind: "tool.decision", ToolName: ptrString("Bash"), PromptID: ptrString("p1"), AgentID: ptrString("root"), DecisionSource: ptrString("user_reject")})
	seedFullEvent(t, pool, eventSeed{Seq: 12004, SessionID: sessionID, TS: base, Kind: "tool.decision", ToolName: ptrString("Edit"), PromptID: ptrString("p2"), AgentID: ptrString("root"), DecisionSource: ptrString("user_reject")})
	seedFullEvent(t, pool, eventSeed{Seq: 12005, SessionID: sessionID, TS: base, Kind: "tool.decision", ToolName: ptrString("Edit"), PromptID: ptrString("p1"), AgentID: ptrString("ag2"), DecisionSource: ptrString("user_reject")})
	seedFullEvent(t, pool, eventSeed{Seq: 12006, SessionID: sessionID, TS: base, Kind: "tool.decision", ToolName: ptrString("Edit"), PromptID: ptrString("p1"), AgentID: ptrString("root"), DecisionSource: ptrString("config")})
	seedFullEvent(t, pool, eventSeed{Seq: 12007, SessionID: otherSessionID, TS: base, Kind: "tool.decision", ToolName: ptrString("Edit"), PromptID: ptrString("p1"), AgentID: ptrString("root"), DecisionSource: ptrString("user_reject")})

	got, _, err := st.ListEvents(context.Background(), store.EventFilter{
		Kinds:          []model.Kind{model.KindToolDecision},
		Tool:           []string{"Edit"},
		DecisionSource: []string{"user_reject"},
		PromptID:       "p1",
		AgentID:        "root",
		Vendor:         []string{"claude_code"},
		Project:        []string{"argus"},
	}, store.Page{Limit: 10})
	require.NoError(t, err)
	require.Len(t, got, 1)
	require.Equal(t, int64(12001), got[0].Seq)
}

func TestListEvents_FromToBoundsTS(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("window")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	base := time.Now().UTC().Add(-24 * time.Hour).Truncate(time.Millisecond)
	ensureRange(t, st, base, base.Add(48*time.Hour))

	seedFullEvent(t, pool, eventSeed{Seq: 13001, SessionID: sessionID, TS: base, Kind: "tool.pre"})
	seedFullEvent(t, pool, eventSeed{Seq: 13002, SessionID: sessionID, TS: base.Add(12 * time.Hour), Kind: "tool.pre"})
	seedFullEvent(t, pool, eventSeed{Seq: 13003, SessionID: sessionID, TS: base.Add(48 * time.Hour), Kind: "tool.pre"})

	from := base.Add(time.Hour)
	to := base.Add(13 * time.Hour)
	got, _, err := st.ListEvents(context.Background(), store.EventFilter{From: &from, To: &to}, store.Page{Limit: 10})
	require.NoError(t, err)
	require.Len(t, got, 1)
	require.Equal(t, int64(13002), got[0].Seq)
}

// --- GetEvent nullable-field round-trip -------------------------------------

func TestGetEvent_NullableNumericAndBooleanFields(t *testing.T) {
	st, pool := newStore(t)
	sessionID := nextTestSessionID("getevent-numeric")
	seedSession(t, pool, sessionSeed{ID: sessionID})
	ts := time.Now().UTC().Truncate(time.Millisecond)
	ensureRange(t, st, ts, ts)

	seedFullEvent(t, pool, eventSeed{Seq: 14001, SessionID: sessionID, TS: ts, Kind: "llm.request", VendorSeq: ptrInt64(7)})
	_, err := pool.Exec(context.Background(), `
		UPDATE events SET input_tokens = 100, output_tokens = 50, cost_usd = 1.23456789, success = true
		WHERE seq = 14001`)
	require.NoError(t, err)

	got, err := st.GetEvent(context.Background(), model.EventRef{TS: ts, Seq: 14001})
	require.NoError(t, err)
	require.NotNil(t, got.VendorSeq)
	require.Equal(t, int64(7), *got.VendorSeq)
	require.NotNil(t, got.InputTokens)
	require.Equal(t, int64(100), *got.InputTokens)
	require.NotNil(t, got.CostUSD)
	require.InDelta(t, 1.23456789, *got.CostUSD, 0.0000001)
	require.NotNil(t, got.Success)
	require.True(t, *got.Success)

	// A second row with everything left NULL exercises the nil branches of
	// int8OrNil/boolOrNil/CostUSD alongside the first row's non-nil ones.
	seedFullEvent(t, pool, eventSeed{Seq: 14002, SessionID: sessionID, TS: ts.Add(time.Second), Kind: "tool.pre"})
	ensureRange(t, st, ts.Add(time.Second), ts.Add(time.Second))
	got2, err := st.GetEvent(context.Background(), model.EventRef{TS: ts.Add(time.Second), Seq: 14002})
	require.NoError(t, err)
	require.Nil(t, got2.VendorSeq)
	require.Nil(t, got2.InputTokens)
	require.Nil(t, got2.CostUSD)
	require.Nil(t, got2.Success)
}
