// Package postgres — read_analytics.go implements store.Reader's
// AnalyticsSummary, AnalyticsSeries, AnalyticsBreakdown, and
// AnalyticsDecisions (SPEC §3.3, §4.3, P3-06). Every query here is a fixed
// statement generated by sqlc from db/queries/read_analytics.sql (SPEC
// §3.3: "sqlc for everything fixed" — AnalyticsFilter's optional OR-set
// filters are expressed inside the SQL itself via a `cardinality(...) = 0
// OR column = ANY(...)` guard, not the hand-built clause-builder category
// ListSessions/ListEvents/ListToolCalls use for genuinely dynamic
// sort/keyset shapes); this file's own job is choosing which fixed query to
// run, converting its rows, and applying the two pieces of logic SQL alone
// cannot express cleanly: SPEC §4.3's model-attributability null/
// not_attributable split, and the dense zero-filled bucket / `other`-folding
// shape of a timeseries.
//
// SPEC §2.5: every analytics read here hits rollup_hourly/rollup_daily,
// except the three reads rollup_hourly structurally cannot answer —
// tool_name/decision_source/error_type breakdowns and the decisions matrix
// (rollup_hourly carries no such columns, SPEC §2.4) read tool_calls
// instead (not `events`, so P3-10's EXPLAIN guard is unaffected — SPEC
// §2.5's index map already grants this same exception to "the drill-down"),
// and dimension=query_source reads sessions.cost_by_query_source directly
// (SPEC §2.4: rollups deliberately carry no query_source dimension; the
// split "lives on sessions only").
package postgres

import (
	"context"
	"fmt"
	"math"
	"sort"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/YohannHommet/argus/server/internal/model"
	"github.com/YohannHommet/argus/server/internal/store"
	"github.com/YohannHommet/argus/server/internal/store/postgres/gen"
)

const (
	// defaultAnalyticsWindow is SPEC §4.1's default analytics window
	// ("Default window -24h for analytics"), applied when the caller
	// leaves AnalyticsFilter.From/To nil.
	defaultAnalyticsWindow = 24 * time.Hour

	// seriesBucketThreshold is SPEC §4.3's bucket auto-selection cutoff:
	// "bucket defaults to hour for windows <= 7 days, day beyond".
	seriesBucketThreshold = 7 * 24 * time.Hour

	// defaultLimitSeries mirrors openapi.yaml's `limit_series` default (8).
	defaultLimitSeries = 8

	// defaultBreakdownLimit / maxBreakdownLimit mirror openapi.yaml's
	// `limit` default (20) and max (500) on GET /api/v1/analytics/breakdown.
	defaultBreakdownLimit = 20
	maxBreakdownLimit     = 500
)

// notAttributableCounters is SPEC §4.3's exact not_attributable[] list for
// Summary under an active `?model=` filter: every counter besides
// api_requests/api_errors/tokens/cost.
var notAttributableCounters = []string{
	"sessions", "turns", "tool_calls", "tool_rejects", "reject_rate", "loc", "active_seconds",
}

// resolveWindow fills in AnalyticsFilter's From/To defaults (SPEC §4.1's
// analytics default window) when the caller left them nil, returning the
// concrete half-open [from, to) bounds every query below applies.
func resolveWindow(f store.AnalyticsFilter, now time.Time) (from, to time.Time) {
	to = now
	if f.To != nil {
		to = *f.To
	}
	from = to.Add(-defaultAnalyticsWindow)
	if f.From != nil {
		from = *f.From
	}
	return from, to
}

// autoBucket implements SPEC §4.3's bucket auto-selection rule.
func autoBucket(from, to time.Time) store.AnalyticsBucket {
	if to.Sub(from) <= seriesBucketThreshold {
		return store.BucketHour
	}
	return store.BucketDay
}

// resolveBucket returns g's bucket if it names one of the two valid values,
// else SPEC §4.3's auto-selected default — the zero value (unset) and any
// other garbage are treated identically, since httpapi is expected to have
// already validated the query parameter before this ever runs.
func resolveBucket(bucket store.AnalyticsBucket, from, to time.Time) store.AnalyticsBucket {
	if bucket == store.BucketHour || bucket == store.BucketDay {
		return bucket
	}
	return autoBucket(from, to)
}

// validGroupBy whitelists store.Grouping.GroupBy's four SPEC §4.3 values;
// anything else (including the zero value) resolves to GroupByNone.
var validGroupBy = map[store.GroupBy]bool{
	store.GroupByProject: true,
	store.GroupByModel:   true,
	store.GroupByVendor:  true,
	store.GroupByNone:    true,
}

func resolveGroupBy(g store.GroupBy) store.GroupBy {
	if validGroupBy[g] {
		return g
	}
	return store.GroupByNone
}

// sourceKindOf maps store.AnalyticsSource onto rollup_hourly/rollup_daily's
// `source` column values (dirty.go's sourceEvent/sourceMetric constants),
// defaulting the zero value to "event" (SPEC §4.3/openapi's documented
// default).
func sourceKindOf(src store.AnalyticsSource) string {
	if src == store.AnalyticsSourceMetric {
		return sourceMetric
	}
	return sourceEvent
}

// orEmptyStrings converts a nil filter slice into a non-nil, zero-length
// one: pgx encodes a nil Go []string as SQL NULL, not an empty array, and
// this file's SQL guards every optional filter with `cardinality(col) = 0`
// — which is NULL, not true, when the argument itself is NULL. Every
// AnalyticsFilter.Project/Vendor/Model value must pass through this before
// becoming a query argument.
func orEmptyStrings(ss []string) []string {
	if ss == nil {
		return []string{}
	}
	return ss
}

// pgTimestamptz converts a time.Time into the pgtype.Timestamptz sqlc's
// generated params expect.
func pgTimestamptz(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: true}
}

// buildAnalyticsCost assembles model.Cost (SPEC §4.3's fleet-level shape,
// no by_query_source split) from the reported/estimated totals — the same
// reported+estimated=usd, estimatedShare=0-when-total-is-0 rule
// buildSessionCost applies to the session-level SPEC §4.3 shape.
func buildAnalyticsCost(reportedUSD, estimatedUSD float64) model.Cost {
	total := reportedUSD + estimatedUSD
	share := 0.0
	if total != 0 {
		share = estimatedUSD / total
	}
	return model.Cost{USD: total, ReportedUSD: reportedUSD, EstimatedUSD: estimatedUSD, EstimatedShare: share}
}

// hourBucketsInRange returns every hour bucket in [from, to) — dense,
// contiguous, one entry even for an hour with zero rollup rows (SPEC §4.3:
// "dense buckets (zero-filled server-side) so ECharts needs no gap
// handling").
func hourBucketsInRange(from, to time.Time) []time.Time {
	buckets := []time.Time{}
	for b := hourBucket(from); b.Before(to); b = b.Add(time.Hour) {
		buckets = append(buckets, b)
	}
	return buckets
}

// dayBucket truncates ts to the day, UTC — rollup_daily's "date_trunc('day',
// ts)" bucket key (SPEC §2.4), the day-granularity counterpart of dirty.go's
// hourBucket.
func dayBucket(ts time.Time) time.Time {
	t := ts.UTC()
	return time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
}

// dayBucketsInRange is hourBucketsInRange's day-granularity counterpart.
func dayBucketsInRange(from, to time.Time) []time.Time {
	buckets := []time.Time{}
	for b := dayBucket(from); b.Before(to); b = b.AddDate(0, 0, 1) {
		buckets = append(buckets, b)
	}
	return buckets
}

// --- AnalyticsSummary ------------------------------------------------------

// AnalyticsSummary implements store.Reader (SPEC §3.3, §4.3). Runs the
// model-attributable sums (api_requests, api_errors, tokens, cost) with
// AnalyticsFilter.Model applied when present, and — only when it is NOT
// present — the non-model-attributable sums (sessions, turns, tool_calls,
// tool_rejects, loc, active_seconds) unfiltered by model. Under an active
// model filter, every non-attributable field is left nil and named in
// NotAttributable instead of being computed at all (SPEC §4.3's "returning
// 0 would misreport a real number as zero").
func (s *Store) AnalyticsSummary(ctx context.Context, f store.AnalyticsFilter) (model.Summary, error) {
	from, to := resolveWindow(f, time.Now())
	q := gen.New(s.pool)
	sourceKind := sourceKindOf(f.Source)
	projects, vendors, models := orEmptyStrings(f.Project), orEmptyStrings(f.Vendor), orEmptyStrings(f.Model)

	attr, err := q.SummaryAttributable(ctx, gen.SummaryAttributableParams{
		FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), SourceKind: sourceKind,
		Projects: projects, Vendors: vendors, Models: models,
	})
	if err != nil {
		return model.Summary{}, fmt.Errorf("postgres: analytics summary: attributable: %w", err)
	}
	reported, err := attr.CostReportedUsd.Float64Value()
	if err != nil {
		return model.Summary{}, fmt.Errorf("postgres: analytics summary: decode cost_reported_usd: %w", err)
	}
	estimated, err := attr.CostEstimatedUsd.Float64Value()
	if err != nil {
		return model.Summary{}, fmt.Errorf("postgres: analytics summary: decode cost_estimated_usd: %w", err)
	}

	summary := model.Summary{
		Window:      model.Window{From: from, To: to, Bucket: string(autoBucket(from, to))},
		APIRequests: attr.ApiRequests,
		APIErrors:   attr.ApiErrors,
		Tokens: model.TokenUsage{
			Input: attr.InputTokens, Output: attr.OutputTokens,
			CacheRead: attr.CacheReadTokens, CacheCreation: attr.CacheCreationTokens,
		},
		Cost:                buildAnalyticsCost(reported.Float64, estimated.Float64),
		Source:              model.Source(sourceKind),
		MetricsOnlyProjects: []string{},
		NotAttributable:     []string{},
	}

	if len(f.Model) > 0 {
		// SPEC §4.3 "Model-filtered requests": every non-model-attributable
		// counter is null, never computed/zeroed, and named here.
		summary.NotAttributable = notAttributableCounters
	} else {
		nonAttr, nonAttrErr := q.SummaryNonAttributable(ctx, gen.SummaryNonAttributableParams{
			FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), SourceKind: sourceKind,
			Projects: projects, Vendors: vendors,
		})
		if nonAttrErr != nil {
			return model.Summary{}, fmt.Errorf("postgres: analytics summary: non-attributable: %w", nonAttrErr)
		}
		sessions, turns := nonAttr.SessionsStarted, nonAttr.Turns
		toolCalls, toolRejects := nonAttr.ToolCalls, nonAttr.ToolRejects
		activeSeconds := nonAttr.ActiveSeconds
		rejectRate := 0.0
		if toolCalls != 0 {
			rejectRate = float64(toolRejects) / float64(toolCalls)
		}
		loc := model.LOC{Added: nonAttr.LocAdded, Removed: nonAttr.LocRemoved}

		summary.Sessions = &sessions
		summary.Turns = &turns
		summary.ToolCalls = &toolCalls
		summary.ToolRejects = &toolRejects
		summary.RejectRate = &rejectRate
		summary.LOC = &loc
		summary.ActiveSeconds = &activeSeconds
	}

	metricsOnly, err := q.MetricsOnlyProjects(ctx, gen.MetricsOnlyProjectsParams{
		FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), Projects: projects, Vendors: vendors,
	})
	if err != nil {
		return model.Summary{}, fmt.Errorf("postgres: analytics summary: metrics-only projects: %w", err)
	}
	summary.MetricsOnlyProjects = metricsOnly

	return summary, nil
}

// --- AnalyticsSeries ---------------------------------------------------

// seriesRow is the plain-Go-typed shape both SeriesHourlyRow and
// SeriesDailyRow convert into (fromSeriesHourlyRow/fromSeriesDailyRow)
// before buildSeries picks the one column Grouping.Metric names — one
// shared conversion/selection path regardless of which rollup table served
// the request.
type seriesRow struct {
	Bucket                                                                 time.Time
	GroupKey                                                               string
	SessionsStarted, Turns, APIRequests, APIErrors, ToolCalls, ToolRejects int64
	InputTokens, OutputTokens, CacheReadTokens, CacheCreationTokens        int64
	CostReportedUSD, CostEstimatedUSD                                      float64
	LocAdded, LocRemoved                                                   int64
}

func fromSeriesHourlyRow(r gen.SeriesHourlyRow) (seriesRow, error) {
	reported, err := r.CostReportedUsd.Float64Value()
	if err != nil {
		return seriesRow{}, fmt.Errorf("decode cost_reported_usd: %w", err)
	}
	estimated, err := r.CostEstimatedUsd.Float64Value()
	if err != nil {
		return seriesRow{}, fmt.Errorf("decode cost_estimated_usd: %w", err)
	}
	return seriesRow{
		Bucket: r.Bucket.Time, GroupKey: r.GroupKey,
		SessionsStarted: r.SessionsStarted, Turns: r.Turns,
		APIRequests: r.ApiRequests, APIErrors: r.ApiErrors,
		ToolCalls: r.ToolCalls, ToolRejects: r.ToolRejects,
		InputTokens: r.InputTokens, OutputTokens: r.OutputTokens,
		CacheReadTokens: r.CacheReadTokens, CacheCreationTokens: r.CacheCreationTokens,
		CostReportedUSD: reported.Float64, CostEstimatedUSD: estimated.Float64,
		LocAdded: r.LocAdded, LocRemoved: r.LocRemoved,
	}, nil
}

func fromSeriesDailyRow(r gen.SeriesDailyRow) (seriesRow, error) {
	reported, err := r.CostReportedUsd.Float64Value()
	if err != nil {
		return seriesRow{}, fmt.Errorf("decode cost_reported_usd: %w", err)
	}
	estimated, err := r.CostEstimatedUsd.Float64Value()
	if err != nil {
		return seriesRow{}, fmt.Errorf("decode cost_estimated_usd: %w", err)
	}
	return seriesRow{
		Bucket: r.Bucket.Time, GroupKey: r.GroupKey,
		SessionsStarted: r.SessionsStarted, Turns: r.Turns,
		APIRequests: r.ApiRequests, APIErrors: r.ApiErrors,
		ToolCalls: r.ToolCalls, ToolRejects: r.ToolRejects,
		InputTokens: r.InputTokens, OutputTokens: r.OutputTokens,
		CacheReadTokens: r.CacheReadTokens, CacheCreationTokens: r.CacheCreationTokens,
		CostReportedUSD: reported.Float64, CostEstimatedUSD: estimated.Float64,
		LocAdded: r.LocAdded, LocRemoved: r.LocRemoved,
	}, nil
}

// metricValue picks the one column store.TimeseriesMetric names (SPEC
// §4.3). cost = reported+estimated (buildAnalyticsCost's USD field);
// tokens = the sum of all four token columns — SPEC names no single
// "tokens" rollup column, and total token volume is the only reading that
// does not silently drop cache tokens; loc = added+removed, similarly the
// only single-number reading of a two-column metric.
func (r seriesRow) metricValue(m store.TimeseriesMetric) float64 {
	switch m {
	case store.MetricCost:
		return r.CostReportedUSD + r.CostEstimatedUSD
	case store.MetricTokens:
		return float64(r.InputTokens + r.OutputTokens + r.CacheReadTokens + r.CacheCreationTokens)
	case store.MetricSessions:
		return float64(r.SessionsStarted)
	case store.MetricTurns:
		return float64(r.Turns)
	case store.MetricAPIRequests:
		return float64(r.APIRequests)
	case store.MetricAPIErrors:
		return float64(r.APIErrors)
	case store.MetricToolCalls:
		return float64(r.ToolCalls)
	case store.MetricToolRejects:
		return float64(r.ToolRejects)
	case store.MetricLOC:
		return float64(r.LocAdded + r.LocRemoved)
	default:
		return 0
	}
}

// buildSeries assembles model.Series from buckets (the dense, contiguous
// bucket list — SPEC §4.3) and rows (one entry per (bucket, group_key) that
// actually had a rollup row). Every distinct group_key becomes its own
// series; a bucket with no row for a given key reads as 0 (Go's
// zero-value-on-missing-map-key), which is exactly SPEC §4.3's "dense
// buckets (zero-filled server-side)". Keys are ranked by their
// metric total across the whole window, descending (ties broken by key for
// determinism); only the top limitSeries are returned as their own
// SeriesPoint, the remainder folds into Other by summing the SAME rows per
// bucket — so sum(series)+other == sum(all rows) per bucket holds by
// construction, never by a separate reconciliation step (SPEC §4.3: "Series
// beyond limit_series fold into other by total desc"). singleSeries, when
// true (group_by=none), guarantees exactly one series with key "" even
// with zero matching rows — so an empty window still returns one all-zero
// series (SPEC's "an empty window returns zeros, not an error") instead of
// no series at all. group_by=project/model/vendor has no equivalent
// obligation: there is no dimension value to report when nothing was seen.
func buildSeries(buckets []time.Time, rows []seriesRow, metric store.TimeseriesMetric, limitSeries int, singleSeries bool) model.Series {
	// Bucket lookups are keyed by UnixNano, never by time.Time itself: two
	// semantically-equal time.Time values (one built by time.Date, one
	// decoded by pgx from a timestamptz column) are not guaranteed to
	// compare equal as a Go map key — Time equality as a map key is a
	// struct compare (wall/ext/loc), not the Equal method — so a raw
	// time.Time key can silently miss and zero-fill every bucket.
	key := func(t time.Time) int64 { return t.UTC().UnixNano() }

	byBucket := map[int64]map[string]float64{}
	totals := map[string]float64{}
	var keyOrder []string
	seen := map[string]bool{}

	if singleSeries {
		seen[""] = true
		keyOrder = append(keyOrder, "")
	}

	for _, r := range rows {
		v := r.metricValue(metric)
		bk := key(r.Bucket)
		if byBucket[bk] == nil {
			byBucket[bk] = map[string]float64{}
		}
		byBucket[bk][r.GroupKey] += v
		totals[r.GroupKey] += v
		if !seen[r.GroupKey] {
			seen[r.GroupKey] = true
			keyOrder = append(keyOrder, r.GroupKey)
		}
	}

	sort.Slice(keyOrder, func(i, j int) bool {
		if totals[keyOrder[i]] != totals[keyOrder[j]] {
			return totals[keyOrder[i]] > totals[keyOrder[j]]
		}
		return keyOrder[i] < keyOrder[j]
	})

	kept := keyOrder
	var folded []string
	if len(keyOrder) > limitSeries {
		kept = keyOrder[:limitSeries]
		folded = keyOrder[limitSeries:]
	}

	series := make([]model.SeriesPoint, len(kept))
	for i, k := range kept {
		values := make([]float64, len(buckets))
		for bi, b := range buckets {
			values[bi] = byBucket[key(b)][k]
		}
		series[i] = model.SeriesPoint{Key: k, Values: values}
	}

	var other *model.SeriesOther
	if len(folded) > 0 {
		foldedSet := make(map[string]bool, len(folded))
		for _, k := range folded {
			foldedSet[k] = true
		}
		values := make([]float64, len(buckets))
		for bi, b := range buckets {
			var sum float64
			for k, v := range byBucket[key(b)] {
				if foldedSet[k] {
					sum += v
				}
			}
			values[bi] = sum
		}
		other = &model.SeriesOther{Values: values}
	}

	return model.Series{Series: series, Other: other}
}

// AnalyticsSeries implements store.Reader (SPEC §3.3, §4.3): dense
// zero-filled buckets, group_by, limit_series + other. Returns
// store.ErrNotAttributable, computing nothing, when Grouping.Metric is not
// model-attributable and AnalyticsFilter.Model is non-empty (SPEC §4.3:
// "metric=sessions with a model filter is a 400").
func (s *Store) AnalyticsSeries(ctx context.Context, f store.AnalyticsFilter, g store.Grouping) (model.Series, error) {
	if len(f.Model) > 0 && !g.Metric.Attributable() {
		return model.Series{}, store.ErrNotAttributable
	}

	from, to := resolveWindow(f, time.Now())
	bucket := resolveBucket(g.Bucket, from, to)
	groupBy := resolveGroupBy(g.GroupBy)
	limitSeries := g.LimitSeries
	if limitSeries <= 0 {
		limitSeries = defaultLimitSeries
	}

	q := gen.New(s.pool)
	sourceKind := sourceKindOf(f.Source)
	projects, vendors, models := orEmptyStrings(f.Project), orEmptyStrings(f.Vendor), orEmptyStrings(f.Model)

	var buckets []time.Time
	var rows []seriesRow

	if bucket == store.BucketDay {
		buckets = dayBucketsInRange(from, to)
		dailyRows, err := q.SeriesDaily(ctx, gen.SeriesDailyParams{
			GroupBy: string(groupBy), FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), SourceKind: sourceKind,
			Projects: projects, Vendors: vendors, Models: models,
		})
		if err != nil {
			return model.Series{}, fmt.Errorf("postgres: analytics series: daily: %w", err)
		}
		for _, r := range dailyRows {
			sr, convErr := fromSeriesDailyRow(r)
			if convErr != nil {
				return model.Series{}, fmt.Errorf("postgres: analytics series: %w", convErr)
			}
			rows = append(rows, sr)
		}
	} else {
		buckets = hourBucketsInRange(from, to)
		hourlyRows, err := q.SeriesHourly(ctx, gen.SeriesHourlyParams{
			GroupBy: string(groupBy), FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), SourceKind: sourceKind,
			Projects: projects, Vendors: vendors, Models: models,
		})
		if err != nil {
			return model.Series{}, fmt.Errorf("postgres: analytics series: hourly: %w", err)
		}
		for _, r := range hourlyRows {
			sr, convErr := fromSeriesHourlyRow(r)
			if convErr != nil {
				return model.Series{}, fmt.Errorf("postgres: analytics series: %w", convErr)
			}
			rows = append(rows, sr)
		}
	}

	series := buildSeries(buckets, rows, g.Metric, limitSeries, groupBy == store.GroupByNone)
	series.Bucket = string(bucket)
	series.Buckets = buckets
	return series, nil
}

// --- AnalyticsBreakdown --------------------------------------------------

// breakdownRow is the plain-Go-typed shape every dimension's query
// converts into before ranking/limiting.
type breakdownRow struct {
	Key   string
	Value float64
}

// breakdownAttributable reports whether a breakdown dimension/metric pair can
// honour a ?model= filter at all. See AnalyticsBreakdown's doc comment: only
// the rollup-sourced dimensions carry a model column, and only cost and
// tokens are model-attributable counters within it. `calls` is excluded even
// on those dimensions because rollup_hourly's tool_calls counter is recorded
// in the model=” group by construction (a tool call has no model), so a
// model-filtered call count could only ever be zero.
func breakdownAttributable(d store.Dimension) bool {
	switch d.Name {
	case store.DimensionModel, store.DimensionProject:
		return d.Metric == store.BreakdownMetricCost || d.Metric == store.BreakdownMetricTokens
	case store.DimensionTool, store.DimensionDecisionSource, store.DimensionErrorType, store.DimensionQuerySource:
		return false
	default:
		return false
	}
}

// AnalyticsBreakdown implements store.Reader (SPEC §3.3, §4.3): top-N by
// dimension. dimension=model|project read rollup_hourly (Dimension.Metric
// selects cost/calls/tokens); dimension=tool|decision_source|error_type
// read tool_calls and always report call counts, since tool_calls has no
// cost/token columns to honor a different Metric with (documented on
// BreakdownToolCalls in read_analytics.sql); dimension=query_source reads
// sessions.cost_by_query_source and always reports cost, the only metric
// that data answers (SPEC §2.4/ticket note: the split "lives on sessions
// only").
//
// Under an active ?model= filter it returns store.ErrNotAttributable for
// every dimension/metric combination that cannot honour that filter, rather
// than answering with a number that looks filtered and is not — SPEC §4.3
// applies the same rule to /breakdown as to /timeseries. Only rollup_hourly
// carries a model dimension, and within it only cost and tokens are
// model-attributable counters (§4.3's attributable list: api_requests,
// api_errors, tokens.*, cost.*), so `dimension=model|project` with
// `metric=cost|tokens` is the whole attributable surface. The tool_calls- and
// sessions-sourced dimensions have no model column at all; before this guard
// they silently dropped the filter and returned fleet-wide totals under a
// per-model question, which is the misreporting §4.1's null-vs-zero rule
// exists to prevent.
func (s *Store) AnalyticsBreakdown(ctx context.Context, f store.AnalyticsFilter, d store.Dimension) (model.Breakdown, error) {
	if len(f.Model) > 0 && !breakdownAttributable(d) {
		return model.Breakdown{}, store.ErrNotAttributable
	}

	from, to := resolveWindow(f, time.Now())
	limit := d.Limit
	if limit <= 0 {
		limit = defaultBreakdownLimit
	}
	if limit > maxBreakdownLimit {
		limit = maxBreakdownLimit
	}
	metric := d.Metric
	if metric == "" {
		metric = store.BreakdownMetricCalls
	}

	q := gen.New(s.pool)
	sourceKind := sourceKindOf(f.Source)
	projects, vendors, models := orEmptyStrings(f.Project), orEmptyStrings(f.Vendor), orEmptyStrings(f.Model)

	var rows []breakdownRow

	switch d.Name {
	case store.DimensionModel, store.DimensionProject:
		groupBy := "model"
		if d.Name == store.DimensionProject {
			groupBy = "project"
		}
		res, err := q.BreakdownRollup(ctx, gen.BreakdownRollupParams{
			GroupBy: groupBy, FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), SourceKind: sourceKind,
			Projects: projects, Vendors: vendors, Models: models,
		})
		if err != nil {
			return model.Breakdown{}, fmt.Errorf("postgres: analytics breakdown: rollup: %w", err)
		}
		for _, r := range res {
			var v float64
			switch metric {
			case store.BreakdownMetricCost:
				cost, costErr := r.Cost.Float64Value()
				if costErr != nil {
					return model.Breakdown{}, fmt.Errorf("postgres: analytics breakdown: decode cost: %w", costErr)
				}
				v = cost.Float64
			case store.BreakdownMetricTokens:
				v = float64(r.Tokens)
			case store.BreakdownMetricCalls:
				v = float64(r.Calls)
			default:
				v = float64(r.Calls)
			}
			rows = append(rows, breakdownRow{Key: r.Key, Value: v})
		}

	case store.DimensionTool, store.DimensionDecisionSource, store.DimensionErrorType:
		res, err := q.BreakdownToolCalls(ctx, gen.BreakdownToolCallsParams{
			Dimension: string(d.Name), FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), Projects: projects,
		})
		if err != nil {
			return model.Breakdown{}, fmt.Errorf("postgres: analytics breakdown: tool calls: %w", err)
		}
		for _, r := range res {
			rows = append(rows, breakdownRow{Key: r.Key, Value: float64(r.Calls)})
		}

	case store.DimensionQuerySource:
		res, err := q.BreakdownQuerySource(ctx, gen.BreakdownQuerySourceParams{
			FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), Projects: projects, Vendors: vendors, Models: models,
		})
		if err != nil {
			return model.Breakdown{}, fmt.Errorf("postgres: analytics breakdown: query source: %w", err)
		}
		for _, r := range res {
			rows = append(rows, breakdownRow{Key: r.Key, Value: r.Cost})
		}

	default:
		return model.Breakdown{}, fmt.Errorf("postgres: analytics breakdown: unknown dimension %q", d.Name)
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Value != rows[j].Value {
			return rows[i].Value > rows[j].Value
		}
		return rows[i].Key < rows[j].Key
	})

	var total float64
	for _, r := range rows {
		total += r.Value
	}
	if len(rows) > limit {
		rows = rows[:limit]
	}

	out := make([]model.BreakdownRow, len(rows))
	for i, r := range rows {
		share := 0.0
		if total != 0 {
			share = r.Value / total
		}
		out[i] = model.BreakdownRow{Key: r.Key, Value: r.Value, Share: share}
	}

	return model.Breakdown{Dimension: string(d.Name), Rows: out}, nil
}

// --- AnalyticsDecisions --------------------------------------------------

// waitPercentiles is one tool_name's p50/p95 wait_ms (nil when every call
// for that tool lacked a wait_ms, matching SessionDetail.TopTools' P50MS
// convention).
type waitPercentiles struct {
	P50MS, P95MS *int64
}

// roundToInt64Ptr rounds a nullable float64 percentile to *int64, preserving
// nil — the DecisionMatrixRow.P50WaitMS/P95WaitMS counterpart of
// read_sessions.go's roundToIntPtr.
func roundToInt64Ptr(f *float64) *int64 {
	if f == nil {
		return nil
	}
	v := int64(math.Round(*f))
	return &v
}

// decisionWaitPercentiles is hand-written pgx, not sqlc, for the same
// percentile_cont NOT-NULL-mis-inference reason read_sessions.go's
// sessionTopTools/sessionHookLatency document: sqlc infers
// percentile_cont's result column as NOT NULL against this schema, which is
// wrong for a tool_name whose every call lacked a wait_ms.
func decisionWaitPercentiles(ctx context.Context, pool *pgxpool.Pool, from, to time.Time, projects []string) (map[string]waitPercentiles, error) {
	rows, err := pool.Query(ctx, `
		SELECT tc.tool_name,
		       percentile_cont(0.5) WITHIN GROUP (ORDER BY tc.wait_ms) AS p50_ms,
		       percentile_cont(0.95) WITHIN GROUP (ORDER BY tc.wait_ms) AS p95_ms
		FROM tool_calls tc
		WHERE tc.started_at >= $1 AND tc.started_at < $2
		  AND (cardinality($3::text[]) = 0
		       OR EXISTS (SELECT 1 FROM sessions s WHERE s.id = tc.session_id AND s.project = ANY($3::text[])))
		GROUP BY tc.tool_name`, from, to, projects)
	if err != nil {
		return nil, fmt.Errorf("postgres: analytics decisions: wait percentiles: %w", err)
	}
	defer rows.Close()

	out := map[string]waitPercentiles{}
	for rows.Next() {
		var toolName string
		var p50, p95 *float64
		if scanErr := rows.Scan(&toolName, &p50, &p95); scanErr != nil {
			return nil, fmt.Errorf("postgres: analytics decisions: scan wait percentiles: %w", scanErr)
		}
		out[toolName] = waitPercentiles{P50MS: roundToInt64Ptr(p50), P95MS: roundToInt64Ptr(p95)}
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("postgres: analytics decisions: wait percentiles: %w", err)
	}
	return out, nil
}

// AnalyticsDecisions implements store.Reader (SPEC §3.3, §4.3): "the matrix
// the product exists for" — accept/reject/by_source/exact_share/wait
// percentiles per tool_name, sourced from tool_calls (SPEC §2.5's
// documented drill-down exception; rollup_hourly carries neither
// decision_source nor per-tool wait_ms, SPEC §2.4). Ignores
// AnalyticsFilter.Model/Vendor/Source — openapi.yaml's decisions endpoint
// exposes only from/to/project, and tool_calls has no model or event/metric
// split to filter on.
func (s *Store) AnalyticsDecisions(ctx context.Context, f store.AnalyticsFilter) (model.DecisionMatrix, error) {
	from, to := resolveWindow(f, time.Now())
	q := gen.New(s.pool)
	projects := orEmptyStrings(f.Project)

	counts, err := q.DecisionCounts(ctx, gen.DecisionCountsParams{
		FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), Projects: projects,
	})
	if err != nil {
		return model.DecisionMatrix{}, fmt.Errorf("postgres: analytics decisions: counts: %w", err)
	}
	bySourceRows, err := q.DecisionBySource(ctx, gen.DecisionBySourceParams{
		FromTs: pgTimestamptz(from), ToTs: pgTimestamptz(to), Projects: projects,
	})
	if err != nil {
		return model.DecisionMatrix{}, fmt.Errorf("postgres: analytics decisions: by source: %w", err)
	}
	waits, err := decisionWaitPercentiles(ctx, s.pool, from, to, projects)
	if err != nil {
		return model.DecisionMatrix{}, err
	}

	bySource := map[string]map[string]int64{}
	for _, r := range bySourceRows {
		if bySource[r.ToolName] == nil {
			bySource[r.ToolName] = map[string]int64{}
		}
		bySource[r.ToolName][r.DecisionSource] = r.N
	}

	rows := make([]model.DecisionMatrixRow, len(counts))
	for i, c := range counts {
		exactShare := 1.0 // vacuously exact when nothing is decided yet (matches read_sessions.go's SessionDecisionSummary convention)
		if c.Decided > 0 {
			exactShare = float64(c.ExactDecided) / float64(c.Decided)
		}
		src := bySource[c.ToolName]
		if src == nil {
			src = map[string]int64{}
		}
		w := waits[c.ToolName]
		rows[i] = model.DecisionMatrixRow{
			ToolName: c.ToolName, Accept: c.Accept, Reject: c.Reject,
			BySource: src, ExactShare: exactShare, P50WaitMS: w.P50MS, P95WaitMS: w.P95MS,
		}
	}

	return model.DecisionMatrix{Rows: rows}, nil
}
