// Package postgres — rollups.go implements store.Maintenance.RunRollups,
// the SPEC §2.4 rollup job: single-flighted via a transaction-scoped
// advisory lock, claiming dirty (bucket, source) pairs from rollup_dirty
// plus the current/previous hour unconditionally, then a full per-bucket
// recompute of rollup_hourly for source='event' and source='metric'
// separately (SPEC §1.8: never summed), followed by a rollup_daily
// recompute for every affected day — all inside the one transaction RunRollups
// opens, so a failure at any step restores rollup_dirty for the next run.
//
// # Why there is no events.seq watermark (SPEC §2.4, review blocker B4)
//
// events.seq is allocated by `GENERATED BY DEFAULT AS IDENTITY` at INSERT
// time, before commit. Two concurrent WriteBatch transactions can allocate
// seq in one order and commit in the other (the slower transaction holds
// the lower seq but commits last). A job that tracked "the highest seq
// processed so far" and only looked at events.seq > watermark on the next
// run would permanently miss the low-seq transaction's rows: by the time it
// commits, the watermark has already moved past its seq. rollup_dirty has
// no such window because the dirty mark is written by markRollupDirty
// (dirty.go) inside the *same* transaction as the events insert — the mark
// and the data it describes become visible atomically together, however
// late that transaction commits relative to any other. RunRollups's claim
// step (ClaimDirtyBuckets) reads rollup_dirty, never events.seq, and that is
// the whole mechanism; see rollups_test.go's B4 test for the concurrency
// scenario this design survives and a seq watermark would not.
package postgres

import (
	"context"
	"fmt"
	"math"
	"sort"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/YohannHommet/argus/server/internal/pricing"
	"github.com/YohannHommet/argus/server/internal/store"
	"github.com/YohannHommet/argus/server/internal/store/postgres/gen"
)

// rollupLockKey is the pg_try_advisory_xact_lock key RunRollups takes to
// single-flight the whole job (SPEC §2.4 step 1). Transaction-scoped
// (pg_try_advisory_xact_lock, not pg_advisory_lock): it releases itself on
// COMMIT or ROLLBACK, so unlike migrate.go's migrationLockKey there is no
// matching unlock call to get right. This continues migrate.go's
// migrationLockKey ("ARGUS01" packed into an int64) numbering — that
// comment, plus this one, is this codebase's only lock-key registry to
// date; the next job that needs one should keep the sequence going rather
// than pick an arbitrary value.
const rollupLockKey int64 = 0x41_52_47_55_53_30_32 // "ARGUS02"

// The seven SPEC §1.8 metric names that feed rollups (claude_code.session.count
// and any unrecognized name are stored in metric_samples but never rolled
// up — SPEC §1.8's table, "no" in the "Feeds rollups" column).
const (
	metricCostUsage        = "claude_code.cost.usage"
	metricTokenUsage       = "claude_code.token.usage"
	metricLinesOfCode      = "claude_code.lines_of_code.count"
	metricActiveTime       = "claude_code.active_time.total"
	metricCommitCount      = "claude_code.commit.count"
	metricPullRequestCount = "claude_code.pull_request.count"
	metricCodeEditDecision = "claude_code.code_edit_tool.decision"
)

// RunRollups implements store.Maintenance.RunRollups (SPEC §2.4). See the
// package doc above for the no-watermark design and rollups_test.go for its
// regression test.
func (s *Store) RunRollups(ctx context.Context, maxBuckets int) (store.RollupStats, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return store.RollupStats{}, fmt.Errorf("postgres: run rollups: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op after a successful Commit

	q := gen.New(tx)

	// SPEC §2.4 step 1: single-flight via a non-blocking, transaction-scoped
	// advisory lock. A second concurrent invocation must return immediately
	// with zero buckets and no error (P3-05 ticket note) — committing this
	// otherwise-empty transaction (rather than rolling it back) is
	// deliberate even though nothing was written: it releases the lock
	// promptly instead of leaving ROLLBACK's slightly slower cleanup path as
	// the only way out.
	locked, err := q.TryRollupLock(ctx, rollupLockKey)
	if err != nil {
		return store.RollupStats{}, fmt.Errorf("postgres: run rollups: advisory lock: %w", err)
	}
	if !locked {
		if commitErr := tx.Commit(ctx); commitErr != nil {
			return store.RollupStats{}, fmt.Errorf("postgres: run rollups: commit (lock skip): %w", commitErr)
		}
		return store.RollupStats{}, nil
	}

	stats, err := s.runRollupsLocked(ctx, tx, q, maxBuckets, time.Now().UTC())
	if err != nil {
		return store.RollupStats{}, err
	}

	if err := tx.Commit(ctx); err != nil {
		return store.RollupStats{}, fmt.Errorf("postgres: run rollups: commit: %w", err)
	}
	return stats, nil
}

// runRollupsLocked runs SPEC §2.4 steps 2-5 once the advisory lock is held:
// claim dirty buckets, union in the current/previous hour unconditionally
// (belt-and-braces plus keeping the live dashboard fresh), recompute
// rollup_hourly for each source separately, then recompute rollup_daily for
// every affected day.
func (s *Store) runRollupsLocked(ctx context.Context, tx pgx.Tx, q *gen.Queries, maxBuckets int, now time.Time) (store.RollupStats, error) {
	claimed, err := q.ClaimDirtyBuckets(ctx, int32(maxBuckets)) //nolint:gosec // maxBuckets is ARGUS_ROLLUP_MAX_BUCKETS, a small positive config value never near int32's range.
	if err != nil {
		return store.RollupStats{}, fmt.Errorf("postgres: run rollups: claim dirty buckets: %w", err)
	}

	eventBuckets := map[time.Time]bool{}
	metricBuckets := map[time.Time]bool{}
	for _, c := range claimed {
		if !c.Bucket.Valid {
			continue
		}
		switch c.Source {
		case sourceEvent:
			eventBuckets[c.Bucket.Time.UTC()] = true
		case sourceMetric:
			metricBuckets[c.Bucket.Time.UTC()] = true
		}
	}

	// SPEC §2.4 step 3: current and previous hour, unconditionally, for
	// both sources.
	curHour := hourBucket(now)
	prevHour := curHour.Add(-time.Hour)
	eventBuckets[curHour] = true
	eventBuckets[prevHour] = true
	metricBuckets[curHour] = true
	metricBuckets[prevHour] = true

	priceRows, err := gen.New(tx).ListModelPrices(ctx)
	if err != nil {
		return store.RollupStats{}, fmt.Errorf("postgres: run rollups: list model prices: %w", err)
	}
	priceRowsConverted := make([]PriceRow, 0, len(priceRows))
	for _, p := range priceRows {
		pp, err := fromModelPrice(p)
		if err != nil {
			return store.RollupStats{}, fmt.Errorf("postgres: run rollups: model price %s: %w", p.Model, err)
		}
		priceRowsConverted = append(priceRowsConverted, pp)
	}
	prices := toPricingPrices(priceRowsConverted)

	if err := recomputeEventBuckets(ctx, tx, q, prices, sortedTimes(eventBuckets)); err != nil {
		return store.RollupStats{}, err
	}
	if err := recomputeMetricBuckets(ctx, tx, q, sortedTimes(metricBuckets)); err != nil {
		return store.RollupStats{}, err
	}

	if err := recomputeDaily(ctx, q, sourceEvent, sortedTimes(eventBuckets)); err != nil {
		return store.RollupStats{}, err
	}
	if err := recomputeDaily(ctx, q, sourceMetric, sortedTimes(metricBuckets)); err != nil {
		return store.RollupStats{}, err
	}

	return store.RollupStats{
		BucketsClaimed:    len(claimed),
		BucketsRecomputed: len(eventBuckets) + len(metricBuckets),
	}, nil
}

// sortedTimes returns the keys of set in ascending order — every downstream
// statement builds its arrays from this so params are deterministic (helps
// EXPLAIN/log correlation across runs, and makes tests reproducible).
func sortedTimes(set map[time.Time]bool) []time.Time {
	out := make([]time.Time, 0, len(set))
	for t := range set {
		out = append(out, t)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Before(out[j]) })
	return out
}

// daysOf returns the distinct UTC day (date_trunc('day', ·)) each bucket in
// buckets falls on, ascending, deduplicated — the set RecomputeRollupDaily
// needs for one source.
func daysOf(buckets []time.Time) []time.Time {
	set := map[time.Time]bool{}
	for _, b := range buckets {
		d := time.Date(b.Year(), b.Month(), b.Day(), 0, 0, 0, 0, time.UTC)
		set[d] = true
	}
	return sortedTimes(set)
}

func toTimestamptz(ts []time.Time) []pgtype.Timestamptz {
	out := make([]pgtype.Timestamptz, len(ts))
	for i, t := range ts {
		out[i] = pgtype.Timestamptz{Time: t, Valid: true}
	}
	return out
}

// recomputeDaily implements SPEC §2.4 step 5 for one source: rollup_daily
// is always derived from rollup_hourly, never from events/metric_samples
// directly, and the affected days are re-derived fully (delete then
// insert) for the same "a key that stopped existing must disappear"
// reason DeleteRollupHourly's doc comment gives.
func recomputeDaily(ctx context.Context, q *gen.Queries, sourceKind string, buckets []time.Time) error {
	days := daysOf(buckets)
	if len(days) == 0 {
		return nil
	}
	dayArgs := toTimestamptz(days)
	if err := q.DeleteRollupDaily(ctx, gen.DeleteRollupDailyParams{Days: dayArgs, SourceKind: sourceKind}); err != nil {
		return fmt.Errorf("postgres: run rollups: delete rollup_daily (%s): %w", sourceKind, err)
	}
	if err := q.InsertRollupDailyFromHourly(ctx, gen.InsertRollupDailyFromHourlyParams{Days: dayArgs, SourceKind: sourceKind}); err != nil {
		return fmt.Errorf("postgres: run rollups: insert rollup_daily (%s): %w", sourceKind, err)
	}
	return nil
}

// --- source='event' pass -------------------------------------------------

// eventGroupKey is rollup_hourly's primary key minus `source` (always
// 'event' here) — shared by both AggregateEventRollup's and
// AggregateToolCallRollup's groups so recomputeEventBuckets can merge them
// (P3-05 defect 1) into one row per key before the single bulk insert.
type eventGroupKey struct {
	bucket                 time.Time
	project, vendor, model string
}

// eventGroupAgg accumulates one eventGroupKey's rollup_hourly columns from
// whichever of AggregateEventRollup/AggregateToolCallRollup produced a row
// for it. costReported/costEstimated stay pgtype.Numeric end-to-end (no
// float round-trip) for the group AggregateEventRollup itself produced;
// tool-call-only groups (a bucket with tool calls but no llm.request/
// session.start/turn.start events for that project/vendor) get a valid
// zero numeric via zeroNumeric so the NOT NULL columns are always
// satisfied.
type eventGroupAgg struct {
	sessionsStarted, turns, apiRequests, apiErrors, toolCalls, toolRejects int32
	inputTokens, outputTokens, cacheReadTokens, cacheCreationTokens        int64
	costReported, costEstimated                                            pgtype.Numeric
}

// recomputeEventBuckets implements SPEC §2.4 step 4's source='event' pass:
// full delete-then-insert recompute of rollup_hourly for buckets. Two
// queries feed it (db/queries/rollups.sql): AggregateEventRollup for
// everything else SQL can compute directly over `events`, and (P3-05
// defect 1) AggregateToolCallRollup for tool_calls/tool_rejects, sourced
// from the `tool_calls` projection instead of the `tool.pre`-only `events`
// count so it is correct on an OTel-only (hooks-disabled) deployment too —
// see AggregateToolCallRollup's SQL comment for the full justification.
// Both queries can produce a row for the very same (bucket, project,
// vendor, model=”) key, and rollup_hourly's delete-then-insert recompute
// has no ON CONFLICT to merge two separate INSERTs with, so this function
// merges them into one eventGroupAgg per key in Go before building the
// single bulk insert. prices (already resolved from model_prices within
// this same transaction) turns each group's uncosted llm.request token
// sums into cost_estimated_usd — the one piece of SPEC §2.4's cost split
// with no SQL equivalent in this codebase.
func recomputeEventBuckets(ctx context.Context, tx pgx.Tx, q *gen.Queries, prices []pricing.Price, buckets []time.Time) error {
	if len(buckets) == 0 {
		return nil
	}
	tsBuckets := toTimestamptz(buckets)

	if err := q.DeleteRollupHourly(ctx, gen.DeleteRollupHourlyParams{Buckets: tsBuckets, SourceKind: sourceEvent}); err != nil {
		return fmt.Errorf("postgres: run rollups: delete event rollup_hourly: %w", err)
	}

	rows, err := q.AggregateEventRollup(ctx, tsBuckets)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: aggregate event rollup: %w", err)
	}

	toolRows, err := q.AggregateToolCallRollup(ctx, tsBuckets)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: aggregate tool_calls rollup: %w", err)
	}

	if len(rows) == 0 && len(toolRows) == 0 {
		return nil
	}

	zeroNumeric, err := numericFromFloat(0)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: zero numeric: %w", err)
	}

	groups := map[eventGroupKey]*eventGroupAgg{}
	var order []eventGroupKey
	get := func(k eventGroupKey) *eventGroupAgg {
		g, ok := groups[k]
		if !ok {
			g = &eventGroupAgg{costReported: zeroNumeric, costEstimated: zeroNumeric}
			groups[k] = g
			order = append(order, k)
		}
		return g
	}

	for _, r := range rows {
		k := eventGroupKey{bucket: r.Bucket.Time, project: r.Project, vendor: r.Vendor, model: r.Model}
		g := get(k)
		g.sessionsStarted = r.SessionsStarted
		g.turns = r.Turns
		g.apiRequests = r.ApiRequests
		g.apiErrors = r.ApiErrors
		g.inputTokens = r.InputTokens
		g.outputTokens = r.OutputTokens
		g.cacheReadTokens = r.CacheReadTokens
		g.cacheCreationTokens = r.CacheCreationTokens
		g.costReported = r.CostReportedUsd

		estimated := 0.0
		uncosted := r.UncostedInputTokens > 0 || r.UncostedOutputTokens > 0 || r.UncostedCacheReadTokens > 0 || r.UncostedCacheCreationTokens > 0
		if r.Model != "" && uncosted {
			tokens := costTokens{
				input: r.UncostedInputTokens, output: r.UncostedOutputTokens,
				cacheRead: r.UncostedCacheReadTokens, cacheWrite: r.UncostedCacheCreationTokens,
			}
			// No resolved price: the group's uncosted tokens contribute
			// nothing to cost_estimated_usd — never a zero standing in for
			// a real price, never dropped from the other already-computed
			// counters (SPEC §2.4, ticket note).
			if usd, ok := estimateCost(prices, r.Model, tokens, r.Bucket.Time); ok {
				estimated = usd
			}
		}
		num, err := numericFromFloat(estimated)
		if err != nil {
			return fmt.Errorf("postgres: run rollups: cost_estimated_usd numeric: %w", err)
		}
		g.costEstimated = num
	}

	// P3-05 defect 1: tool_calls/tool_rejects always land in the model=''
	// group (a tool call is never model-attributable, SPEC §2.4), merged
	// additively into whatever eventGroupAgg that key already has (or a
	// freshly zeroed one if AggregateEventRollup produced no row for it —
	// e.g. a bucket with tool calls but no session.start/turn.start/
	// llm.request events for that project/vendor).
	for _, r := range toolRows {
		k := eventGroupKey{bucket: r.Bucket.Time, project: r.Project, vendor: r.Vendor, model: ""}
		g := get(k)
		g.toolCalls = r.ToolCalls
		g.toolRejects = r.ToolRejects
	}

	sort.Slice(order, func(i, j int) bool {
		a, b := order[i], order[j]
		if !a.bucket.Equal(b.bucket) {
			return a.bucket.Before(b.bucket)
		}
		if a.project != b.project {
			return a.project < b.project
		}
		if a.vendor != b.vendor {
			return a.vendor < b.vendor
		}
		return a.model < b.model
	})

	n := len(order)
	ins := eventRollupInsert{
		bucket: make([]time.Time, n), project: make([]string, n), vendor: make([]string, n), model: make([]string, n),
		sessionsStarted: make([]int32, n), turns: make([]int32, n), apiRequests: make([]int32, n), apiErrors: make([]int32, n),
		toolCalls: make([]int32, n), toolRejects: make([]int32, n),
		inputTokens: make([]int64, n), outputTokens: make([]int64, n), cacheReadTokens: make([]int64, n), cacheCreationTokens: make([]int64, n),
		costReported: make([]pgtype.Numeric, n), costEstimated: make([]pgtype.Numeric, n),
	}
	for i, k := range order {
		g := groups[k]
		ins.bucket[i] = k.bucket
		ins.project[i] = k.project
		ins.vendor[i] = k.vendor
		ins.model[i] = k.model
		ins.sessionsStarted[i] = g.sessionsStarted
		ins.turns[i] = g.turns
		ins.apiRequests[i] = g.apiRequests
		ins.apiErrors[i] = g.apiErrors
		ins.toolCalls[i] = g.toolCalls
		ins.toolRejects[i] = g.toolRejects
		ins.inputTokens[i] = g.inputTokens
		ins.outputTokens[i] = g.outputTokens
		ins.cacheReadTokens[i] = g.cacheReadTokens
		ins.cacheCreationTokens[i] = g.cacheCreationTokens
		ins.costReported[i] = g.costReported
		ins.costEstimated[i] = g.costEstimated
	}

	if err := insertEventRollupHourly(ctx, tx, ins); err != nil {
		return err
	}
	return nil
}

// costTokens is one group's uncosted llm.request token sums — the input to
// estimateCost.
type costTokens struct {
	input, output, cacheRead, cacheWrite int64
}

// toPricingPrices converts the []PriceRow this transaction already resolved
// from model_prices into the []pricing.Price internal/pricing.Estimate
// wants — the one pgtype/plain-Go-type boundary crossing this package's doc
// comment describes, done once per RunRollups pass rather than per group.
func toPricingPrices(prices []PriceRow) []pricing.Price {
	out := make([]pricing.Price, len(prices))
	for i, p := range prices {
		out[i] = pricing.Price{
			Model:             p.Model,
			EffectiveFrom:     p.EffectiveFrom,
			InputPerMTok:      p.InputPerMTok,
			OutputPerMTok:     p.OutputPerMTok,
			CacheReadPerMTok:  p.CacheReadPerMTok,
			CacheWritePerMTok: p.CacheWritePerMTok,
		}
	}
	return out
}

// estimateCost resolves model's price at `at` and prices tokens via
// internal/pricing.Estimate (SPEC §2.4's lookup rule: "latest
// effective_from <= event date, exact model, else longest matching
// prefix") — the single implementation of that algorithm (see defect 2's
// fix: this file used to duplicate it because depguard's "store" rule
// denied internal/query/pricing to internal/store; internal/pricing is a
// leaf package depguard permits, see its package doc). ok=false is exactly
// pricing.ErrNoPrice's condition — the caller must never substitute zero or
// another model's price.
func estimateCost(prices []pricing.Price, model string, tokens costTokens, at time.Time) (usd float64, ok bool) {
	usd, err := pricing.Estimate(prices, model, pricing.Tokens{
		Input: tokens.input, Output: tokens.output,
		CacheRead: tokens.cacheRead, CacheWrite: tokens.cacheWrite,
	}, at)
	if err != nil {
		return 0, false
	}
	return usd, true
}

// eventRollupInsert holds the parallel column arrays insertEventRollupHourly
// bulk-inserts via unnest — the same "build slices, one INSERT ... SELECT *
// FROM unnest(...)" shape as insertMetricSamples (write_metrics.go) and
// upsertSessions.
type eventRollupInsert struct {
	bucket                                                                 []time.Time
	project, vendor, model                                                 []string
	sessionsStarted, turns, apiRequests, apiErrors, toolCalls, toolRejects []int32
	inputTokens, outputTokens, cacheReadTokens, cacheCreationTokens        []int64
	costReported, costEstimated                                            []pgtype.Numeric
}

// insertEventRollupHourly is the hand-written pgx counterpart of
// AggregateEventRollup's SQL comment: sqlc v1.31.1 cannot resolve a
// multi-array `unnest($1::t1[], …)` table function used as a FROM source
// (see db/queries/rollups.sql), so this bulk insert is issued directly
// against tx, exactly like insertMetricSamples/upsertSessions/
// execToolCallUpsert already do for the same reason. No ON CONFLICT: the
// matching bucket/source rows were deleted by DeleteRollupHourly earlier in
// this same transaction.
func insertEventRollupHourly(ctx context.Context, tx pgx.Tx, ins eventRollupInsert) error {
	_, err := tx.Exec(ctx, `
		INSERT INTO rollup_hourly (
			bucket, project, vendor, model, source,
			sessions_started, turns, api_requests, api_errors, tool_calls, tool_rejects,
			input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens,
			cost_reported_usd, cost_estimated_usd
		)
		SELECT b, p, v, m, 'event', ss, tn, ar, ae, tc, tr, it, ot, crt, cct, crr, cer
		FROM unnest(
			$1::timestamptz[], $2::text[], $3::text[], $4::text[],
			$5::int[], $6::int[], $7::int[], $8::int[], $9::int[], $10::int[],
			$11::bigint[], $12::bigint[], $13::bigint[], $14::bigint[],
			$15::numeric[], $16::numeric[]
		) AS t(b, p, v, m, ss, tn, ar, ae, tc, tr, it, ot, crt, cct, crr, cer)`,
		ins.bucket, ins.project, ins.vendor, ins.model,
		ins.sessionsStarted, ins.turns, ins.apiRequests, ins.apiErrors, ins.toolCalls, ins.toolRejects,
		ins.inputTokens, ins.outputTokens, ins.cacheReadTokens, ins.cacheCreationTokens,
		ins.costReported, ins.costEstimated,
	)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: insert event rollup_hourly: %w", err)
	}
	return nil
}

// --- source='metric' pass -------------------------------------------------

// recomputeMetricBuckets implements SPEC §2.4 step 4's source='metric' pass
// and §1.8's cumulative-diffing step: full delete-then-insert recompute of
// rollup_hourly for buckets, driven by FetchMetricRowsForRollup (db/queries/
// rollups.sql) plus the Go-side metric-name -> rollup-column mapping SPEC
// §1.8's table describes (there is no SQL-only way to express "attrs->>
// 'type' picks the column" cleanly across seven differently-shaped
// metrics, so this pass computes in Go and bulk-writes once, exactly like
// the event pass).
func recomputeMetricBuckets(ctx context.Context, tx pgx.Tx, q *gen.Queries, buckets []time.Time) error {
	if len(buckets) == 0 {
		return nil
	}
	tsBuckets := toTimestamptz(buckets)

	if err := q.DeleteRollupHourly(ctx, gen.DeleteRollupHourlyParams{Buckets: tsBuckets, SourceKind: sourceMetric}); err != nil {
		return fmt.Errorf("postgres: run rollups: delete metric rollup_hourly: %w", err)
	}

	rows, err := q.FetchMetricRowsForRollup(ctx, tsBuckets)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: fetch metric rows: %w", err)
	}
	if len(rows) == 0 {
		return nil
	}

	contribution, sampleUpdates, stateUpdates, err := computeMetricDeltas(ctx, tx, rows)
	if err != nil {
		return err
	}

	if len(sampleUpdates) > 0 {
		if err := updateMetricSampleDeltas(ctx, tx, sampleUpdates); err != nil {
			return err
		}
	}
	if len(stateUpdates) > 0 {
		if err := upsertMetricSeriesState(ctx, tx, stateUpdates); err != nil {
			return err
		}
	}

	groups := aggregateMetricGroups(rows, contribution)
	if len(groups) == 0 {
		return nil
	}
	return insertMetricRollupHourly(ctx, tx, groups)
}

// sampleDeltaUpdate is one metric_samples.delta write-back
// (updateMetricSampleDeltas), keyed on the table's full primary key.
type sampleDeltaUpdate struct {
	ts         time.Time
	seriesHash []byte
	dedupKey   string
	delta      float64
}

// seriesStateUpdate is one metric_series_state checkpoint advance
// (upsertMetricSeriesState).
type seriesStateUpdate struct {
	seriesHash []byte
	lastTS     time.Time
	lastValue  float64
}

// computeMetricDeltas walks rows (already ordered by (series_hash, ts) by
// FetchMetricRowsForRollup's ORDER BY) and returns, per row, its rollup
// contribution — SPEC §1.8:
//
//   - cumulative: value minus the previous point's raw value, using
//     fetchSeriesAnchors/metric_series_state as the baseline for each
//     series' first row in this batch; a negative diff (a counter reset)
//     takes the raw value instead.
//   - delta: the value itself — it is already an increment, no diffing
//     needed.
//   - gauge (or any other/unrecognized temporality string — SPEC §0
//     forbids rejecting a vendor-supplied value, and "sum every raw
//     gauge reading" is never correct): the latest-ts row wins, once per
//     (series, hour bucket) — every other row in that (series, bucket)
//     pair contributes 0.
//
// It also returns the metric_samples.delta write-backs for cumulative rows
// and the metric_series_state checkpoint advances for every series that had
// at least one cumulative row, so recomputeMetricBuckets can persist both
// alongside the rollup_hourly write in the same transaction.
func computeMetricDeltas(ctx context.Context, tx pgx.Tx, rows []gen.FetchMetricRowsForRollupRow) ([]float64, []sampleDeltaUpdate, []seriesStateUpdate, error) {
	contribution := make([]float64, len(rows))

	type span struct{ start, end int } // [start, end) into rows; contiguous because rows are series_hash-ordered
	spans := map[string]span{}
	var order []string
	for i, r := range rows {
		key := string(r.SeriesHash)
		sp, ok := spans[key]
		if !ok {
			order = append(order, key)
			spans[key] = span{start: i, end: i + 1}
			continue
		}
		sp.end = i + 1
		spans[key] = sp
	}

	var anchorSeries [][]byte
	var anchorBefore []time.Time
	for _, key := range order {
		sp := spans[key]
		hasCumulative := false
		minTS := rows[sp.start].Ts.Time
		for i := sp.start; i < sp.end; i++ {
			if rows[i].Temporality == "cumulative" {
				hasCumulative = true
			}
			if rows[i].Ts.Time.Before(minTS) {
				minTS = rows[i].Ts.Time
			}
		}
		if hasCumulative {
			anchorSeries = append(anchorSeries, []byte(key))
			anchorBefore = append(anchorBefore, minTS)
		}
	}

	anchors := map[string]*float64{}
	if len(anchorSeries) > 0 {
		found, err := fetchSeriesAnchors(ctx, tx, anchorSeries, anchorBefore)
		if err != nil {
			return nil, nil, nil, err
		}
		anchors = found

		var missing [][]byte
		for _, key := range anchorSeries {
			if _, ok := anchors[string(key)]; !ok {
				missing = append(missing, key)
			}
		}
		if len(missing) > 0 {
			// The direct metric_samples lookback found nothing for these
			// series: either they have no history before this batch, or
			// their history's partition was already dropped by retention.
			// metric_series_state exists for exactly the second case (SPEC
			// §1.8).
			stateRows, err := gen.New(tx).FetchSeriesState(ctx, missing)
			if err != nil {
				return nil, nil, nil, fmt.Errorf("postgres: run rollups: fetch series state: %w", err)
			}
			for _, sr := range stateRows {
				v := sr.LastValue
				anchors[string(sr.SeriesHash)] = &v
			}
		}
	}

	var sampleUpdates []sampleDeltaUpdate
	var stateUpdates []seriesStateUpdate

	for _, key := range order {
		sp := spans[key]
		prev := anchors[key] // *float64, nil means "no known prior value"
		gaugeWinner := map[time.Time]int{}

		for i := sp.start; i < sp.end; i++ {
			r := rows[i]
			switch r.Temporality {
			case "cumulative":
				var delta float64
				if prev == nil || r.Value < *prev {
					delta = r.Value // counter reset (or first-ever point): take the raw value
				} else {
					delta = r.Value - *prev
				}
				v := r.Value
				prev = &v
				contribution[i] = delta
				sampleUpdates = append(sampleUpdates, sampleDeltaUpdate{ts: r.Ts.Time, seriesHash: r.SeriesHash, dedupKey: r.DedupKey, delta: delta})
			case "delta":
				contribution[i] = r.Value
			default: // "gauge" and any other/unrecognized temporality (SPEC §0)
				gaugeWinner[hourBucket(r.Ts.Time)] = i
			}
		}
		for _, idx := range gaugeWinner {
			contribution[idx] = rows[idx].Value
		}
		if prev != nil {
			last := rows[sp.end-1]
			stateUpdates = append(stateUpdates, seriesStateUpdate{seriesHash: last.SeriesHash, lastTS: last.Ts.Time, lastValue: *prev})
		}
	}

	return contribution, sampleUpdates, stateUpdates, nil
}

// fetchSeriesAnchors is the hand-written pgx counterpart of the SQL
// FetchSeriesAnchors comment in db/queries/rollups.sql (same
// multi-array-unnest limitation as insertEventRollupHourly): for each
// (series_hash, before_ts) pair, the value of the latest metric_samples row
// strictly before before_ts for that series, via a LATERAL join so this
// stays one round trip regardless of how many series are in scope. A
// series with no such row is simply absent from the returned map.
func fetchSeriesAnchors(ctx context.Context, tx pgx.Tx, seriesHash [][]byte, beforeTS []time.Time) (map[string]*float64, error) {
	rows, err := tx.Query(ctx, `
		SELECT req.series_hash, prev.value
		FROM unnest($1::bytea[], $2::timestamptz[]) AS req(series_hash, before_ts)
		LEFT JOIN LATERAL (
			SELECT value FROM metric_samples p
			WHERE p.series_hash = req.series_hash AND p.ts < req.before_ts
			ORDER BY p.ts DESC
			LIMIT 1
		) prev ON true`,
		seriesHash, beforeTS)
	if err != nil {
		return nil, fmt.Errorf("postgres: run rollups: fetch series anchors: %w", err)
	}
	defer rows.Close()

	out := map[string]*float64{}
	for rows.Next() {
		var sh []byte
		var v *float64
		if err := rows.Scan(&sh, &v); err != nil {
			return nil, fmt.Errorf("postgres: run rollups: scan series anchor: %w", err)
		}
		if v != nil {
			out[string(sh)] = v
		}
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("postgres: run rollups: fetch series anchors: %w", err)
	}
	return out, nil
}

// updateMetricSampleDeltas is the hand-written pgx counterpart of the SQL
// UpdateMetricSampleDeltas comment (same multi-array-unnest limitation).
func updateMetricSampleDeltas(ctx context.Context, tx pgx.Tx, updates []sampleDeltaUpdate) error {
	n := len(updates)
	ts := make([]time.Time, n)
	seriesHash := make([][]byte, n)
	dedupKey := make([]string, n)
	delta := make([]float64, n)
	for i, u := range updates {
		ts[i], seriesHash[i], dedupKey[i], delta[i] = u.ts, u.seriesHash, u.dedupKey, u.delta
	}
	_, err := tx.Exec(ctx, `
		UPDATE metric_samples ms SET delta = u.delta
		FROM unnest($1::timestamptz[], $2::bytea[], $3::text[], $4::float8[]) AS u(ts, series_hash, dedup_key, delta)
		WHERE ms.ts = u.ts AND ms.series_hash = u.series_hash AND ms.dedup_key = u.dedup_key`,
		ts, seriesHash, dedupKey, delta)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: update metric sample deltas: %w", err)
	}
	return nil
}

// upsertMetricSeriesState is the hand-written pgx counterpart of the SQL
// UpsertMetricSeriesState comment (same multi-array-unnest limitation); see
// that comment for the monotonic-checkpoint WHERE guard's reasoning.
func upsertMetricSeriesState(ctx context.Context, tx pgx.Tx, updates []seriesStateUpdate) error {
	n := len(updates)
	seriesHash := make([][]byte, n)
	lastTS := make([]time.Time, n)
	lastValue := make([]float64, n)
	for i, u := range updates {
		seriesHash[i], lastTS[i], lastValue[i] = u.seriesHash, u.lastTS, u.lastValue
	}
	_, err := tx.Exec(ctx, `
		INSERT INTO metric_series_state (series_hash, last_ts, last_value)
		SELECT * FROM unnest($1::bytea[], $2::timestamptz[], $3::float8[])
		ON CONFLICT (series_hash) DO UPDATE
			SET last_ts = EXCLUDED.last_ts, last_value = EXCLUDED.last_value
			WHERE metric_series_state.last_ts < EXCLUDED.last_ts`,
		seriesHash, lastTS, lastValue)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: upsert metric series state: %w", err)
	}
	return nil
}

// metricGroupKey is rollup_hourly's primary key minus `source` (always
// 'metric' here).
type metricGroupKey struct {
	bucket                 time.Time
	project, vendor, model string
}

// metricGroupAgg accumulates one metricGroupKey's rollup_hourly columns —
// only the ones SPEC §1.8's metric table ever feeds; every other column
// keeps the table's DEFAULT 0.
type metricGroupAgg struct {
	inputTokens, outputTokens, cacheReadTokens, cacheCreationTokens int64
	costReported                                                    float64
	locAdded, locRemoved, activeSeconds                             int64
	commits, pullRequests                                           int32
	editAccept, editReject                                          int32
}

// aggregateMetricGroups implements SPEC §1.8's metric-name -> rollup-column
// table in Go: each FetchMetricRowsForRollup row's contribution (from
// computeMetricDeltas) is routed to the column its metric name feeds,
// grouped by (bucket, project, vendor, model). loc_added/loc_removed,
// active_seconds, commits, pull_requests, and edit_decisions_* are never
// model-attributable (SPEC §1.8, and P3-06's not_attributable list), so
// they always group under model="" regardless of any model attribute the
// raw metric happens to carry (lines_of_code.count does); only
// cost.usage/token.usage are model-attributable. claude_code.session.count
// and any unrecognized metric name are dropped here — SPEC §1.8: "no" in
// the "Feeds rollups" column.
func aggregateMetricGroups(rows []gen.FetchMetricRowsForRollupRow, contribution []float64) map[metricGroupKey]*metricGroupAgg {
	groups := map[metricGroupKey]*metricGroupAgg{}
	get := func(bucket time.Time, project, vendor, model string) *metricGroupAgg {
		k := metricGroupKey{bucket: bucket, project: project, vendor: vendor, model: model}
		g, ok := groups[k]
		if !ok {
			g = &metricGroupAgg{}
			groups[k] = g
		}
		return g
	}

	for i, r := range rows {
		c := contribution[i]
		bucket := hourBucket(r.Ts.Time)
		switch r.Name {
		case metricCostUsage:
			get(bucket, r.Project, r.Vendor, r.AttrModel).costReported += c
		case metricTokenUsage:
			g := get(bucket, r.Project, r.Vendor, r.AttrModel)
			switch r.AttrType {
			case "input":
				g.inputTokens += roundInt64(c)
			case "output":
				g.outputTokens += roundInt64(c)
			case "cacheRead":
				g.cacheReadTokens += roundInt64(c)
			case "cacheCreation":
				g.cacheCreationTokens += roundInt64(c)
			}
		case metricLinesOfCode:
			g := get(bucket, r.Project, r.Vendor, "")
			switch r.AttrType {
			case "added":
				g.locAdded += roundInt64(c)
			case "removed":
				g.locRemoved += roundInt64(c)
			}
		case metricActiveTime:
			get(bucket, r.Project, r.Vendor, "").activeSeconds += roundInt64(c)
		case metricCommitCount:
			get(bucket, r.Project, r.Vendor, "").commits += roundInt32(c)
		case metricPullRequestCount:
			get(bucket, r.Project, r.Vendor, "").pullRequests += roundInt32(c)
		case metricCodeEditDecision:
			g := get(bucket, r.Project, r.Vendor, "")
			switch r.AttrDecision {
			case "accept":
				g.editAccept += roundInt32(c)
			case "reject":
				g.editReject += roundInt32(c)
			}
		default:
			// claude_code.session.count and any unrecognized metric name.
		}
	}
	return groups
}

// roundInt64/roundInt32 convert a computed contribution (a float64 delta)
// back to the integer rollup columns it feeds. Every metric routed through
// them reports whole-number values (token counts, LOC counts, seconds,
// decision counts) — rounding rather than truncating guards against a
// stray float rounding error in the cumulative-diff subtraction flipping,
// say, 3.0000000001 into a truncated 3 vs. -0.0000000001 into 0 either way,
// which would be the same outcome, but 2.9999999998 truncating to 2 would
// not be.
func roundInt64(f float64) int64 { return int64(math.Round(f)) }
func roundInt32(f float64) int32 { return int32(math.Round(f)) }

// insertMetricRollupHourly is the hand-written pgx counterpart of the SQL
// InsertMetricRollupHourly comment (same multi-array-unnest limitation). No
// ON CONFLICT: the matching bucket/source rows were deleted by
// DeleteRollupHourly earlier in this same transaction.
func insertMetricRollupHourly(ctx context.Context, tx pgx.Tx, groups map[metricGroupKey]*metricGroupAgg) error {
	keys := make([]metricGroupKey, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if !keys[i].bucket.Equal(keys[j].bucket) {
			return keys[i].bucket.Before(keys[j].bucket)
		}
		if keys[i].project != keys[j].project {
			return keys[i].project < keys[j].project
		}
		if keys[i].vendor != keys[j].vendor {
			return keys[i].vendor < keys[j].vendor
		}
		return keys[i].model < keys[j].model
	})

	n := len(keys)
	bucket := make([]time.Time, n)
	project := make([]string, n)
	vendor := make([]string, n)
	model := make([]string, n)
	inputTokens := make([]int64, n)
	outputTokens := make([]int64, n)
	cacheReadTokens := make([]int64, n)
	cacheCreationTokens := make([]int64, n)
	costReported := make([]pgtype.Numeric, n)
	locAdded := make([]int64, n)
	locRemoved := make([]int64, n)
	activeSeconds := make([]int64, n)
	commits := make([]int32, n)
	pullRequests := make([]int32, n)
	editAccept := make([]int32, n)
	editReject := make([]int32, n)

	for i, k := range keys {
		g := groups[k]
		bucket[i], project[i], vendor[i], model[i] = k.bucket, k.project, k.vendor, k.model
		inputTokens[i], outputTokens[i] = g.inputTokens, g.outputTokens
		cacheReadTokens[i], cacheCreationTokens[i] = g.cacheReadTokens, g.cacheCreationTokens
		num, err := numericFromFloat(g.costReported)
		if err != nil {
			return fmt.Errorf("postgres: run rollups: metric cost_reported_usd numeric: %w", err)
		}
		costReported[i] = num
		locAdded[i], locRemoved[i], activeSeconds[i] = g.locAdded, g.locRemoved, g.activeSeconds
		commits[i], pullRequests[i] = g.commits, g.pullRequests
		editAccept[i], editReject[i] = g.editAccept, g.editReject
	}

	_, err := tx.Exec(ctx, `
		INSERT INTO rollup_hourly (
			bucket, project, vendor, model, source,
			input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens, cost_reported_usd,
			loc_added, loc_removed, active_seconds, commits, pull_requests,
			edit_decisions_accept, edit_decisions_reject
		)
		SELECT b, p, v, m, 'metric', it, ot, crt, cct, cr, la, lr, asec, cm, pr, eda, edr
		FROM unnest(
			$1::timestamptz[], $2::text[], $3::text[], $4::text[],
			$5::bigint[], $6::bigint[], $7::bigint[], $8::bigint[], $9::numeric[],
			$10::bigint[], $11::bigint[], $12::bigint[],
			$13::int[], $14::int[], $15::int[], $16::int[]
		) AS t(b, p, v, m, it, ot, crt, cct, cr, la, lr, asec, cm, pr, eda, edr)`,
		bucket, project, vendor, model,
		inputTokens, outputTokens, cacheReadTokens, cacheCreationTokens, costReported,
		locAdded, locRemoved, activeSeconds,
		commits, pullRequests, editAccept, editReject,
	)
	if err != nil {
		return fmt.Errorf("postgres: run rollups: insert metric rollup_hourly: %w", err)
	}
	return nil
}
